Repository argilla-io/distilabel, pull requests merged in 2023-12, with the labels that each got.

#139 Fix `llama-cpp` and `hf-inference-endpoints` extras in `pyproject.toml`
  pyproject.toml
Labels: bug, dependencies

#140 Fix `llama_cpp_python` dependency check
  .gitignore
  src/distilabel/utils/imports.py
Labels: bug, dependencies

#141 adds accelerate example
  examples/pipeline-accelerate-and-openai.py
Labels: size:L, example

#146 Add a dry-run when calling `Pipeline.generate`
  src/distilabel/llm/huggingface/transformers.py
  src/distilabel/pipeline.py
Labels: bug, enhancement, size:M, lgtm

#147 Add Notus format in `Prompt.format_as` and update `examples/*.py`
  examples/inference-endpoints-llm-custom-task.py
  examples/pipeline-accelerate-and-openai.py
  examples/pipeline-fn-ultrafeedback-labeller.py
  examples/pipeline-fn-ultrafeedback.py
  examples/pipeline-llamacpp-and-openai.py
  examples/pipeline-selfinstruct-math-openai.py
  examples/pipeline-transformers-and-openai.py
  examples/pipeline-vllm-and-openai.py
  src/distilabel/tasks/__init__.py
  src/distilabel/tasks/prompt.py
  src/distilabel/tasks/text_generation/self_instruct.py
Labels: enhancement, size:L, example, lgtm

#152 Adds `CritiqueTask`, `UltraCMTask` and more
  examples/pipeline-ultracm.py
  pyproject.toml
  src/distilabel/llm/llama_cpp.py
  src/distilabel/tasks/_templates/ultracm.jinja2
  src/distilabel/tasks/critique/__init__.py
  src/distilabel/tasks/critique/base.py
  src/distilabel/tasks/critique/ultracm.py
Labels: enhancement

#159 Add `to_argilla_{dataset,record}` methods in `TextGenerationTask`
  src/distilabel/pipeline.py
  src/distilabel/tasks/_templates/self-instruct.jinja2
  src/distilabel/tasks/text_generation/base.py
  src/distilabel/tasks/text_generation/self_instruct.py
Labels: enhancement

#160 Fix `UltraFeedbackTask.to_argilla_dataset` ratings values
  src/distilabel/tasks/preference/ultrafeedback.py
Labels: fix

#161 Align `typing` and `typing_extensions` with supported Python versions
  src/distilabel/llm/utils.py
  src/distilabel/progress_bar.py
  src/distilabel/tasks/critique/ultracm.py
  src/distilabel/tasks/preference/judgelm.py
  src/distilabel/tasks/preference/ultrafeedback.py
  src/distilabel/tasks/prompt.py
  src/distilabel/utils/types.py
Labels: fix

#163 Add `test` workflow
  .github/workflows/test.yml
  Makefile
  pyproject.toml
  src/distilabel/llm/base.py
  src/distilabel/pipeline.py
  src/distilabel/tasks/base.py
  src/distilabel/tasks/text_generation/base.py
  src/distilabel/utils/types.py
Labels: ci

#164 Update `LLM` to return `Future[List[List[LLMOutput]]]`
  examples/pipeline-pool-llm.py
  src/distilabel/llm/base.py
  src/distilabel/pipeline.py
  src/distilabel/utils/futures.py
  src/distilabel/utils/types.py
Labels: enhancement

#165 Add `PrometheusTask`
  examples/pipeline-prometheus.py
  src/distilabel/tasks/_templates/prometheus.jinja2
  src/distilabel/tasks/critique/base.py
  src/distilabel/tasks/critique/prometheus.py
  src/distilabel/tasks/critique/ultracm.py
Labels: enhancement

#167 Randomise generations order
  src/distilabel/pipeline.py
Labels: enhancement

#169 Add custom `to_argilla_{dataset,record}` to `SelfInstructTask`
  src/distilabel/tasks/base.py
  src/distilabel/tasks/text_generation/base.py
  src/distilabel/tasks/text_generation/self_instruct.py
Labels: enhancement

#170 Fix `shuffle_before_labelling` and progress bar in `Pipeline.generate`
  src/distilabel/pipeline.py
Labels: fix

#171 Replace `multiprocessing` with `multiprocess`
  examples/pipeline-llamacpp-and-openai-process.py
  pyproject.toml
  src/distilabel/llm/base.py
Labels: fix

#172 Fix `SelfInstructTask.{parse_output,to_argilla_record}` methods and `_build_dataset`
  src/distilabel/dataset.py
  src/distilabel/pipeline.py
  src/distilabel/tasks/text_generation/self_instruct.py
Labels: fix

#173 Fix `results` didn't have same order as `futures`
  src/distilabel/utils/futures.py
Labels: fix

#175 Add `{generation,labelling}_model` column as metadata in Argilla
  src/distilabel/dataset.py
  src/distilabel/pipeline.py
  src/distilabel/tasks/base.py
  src/distilabel/tasks/preference/base.py
  src/distilabel/tasks/preference/ultrafeedback.py
  src/distilabel/tasks/text_generation/base.py
  src/distilabel/tasks/text_generation/self_instruct.py
  src/distilabel/utils/argilla.py
Labels: enhancement

#176 Update docs to include info about `ProcessLLM` and `LLMPool`
  .pre-commit-config.yaml
  docs/snippets/guides/self-instruct.py
  docs/snippets/technical-reference/llm/llamacpp_generate.py
  docs/snippets/technical-reference/llm/llmpool.py
  docs/snippets/technical-reference/llm/openai_generate.py
  docs/snippets/technical-reference/llm/processllm.py
  docs/snippets/technical-reference/llm/transformers_generate.py
  docs/snippets/technical-reference/llm/vllm_generate.py
  docs/snippets/technical-reference/pipeline/argilla.py
  docs/snippets/technical-reference/pipeline/pipe_1.py
  docs/snippets/technical-reference/pipeline/pipe_2.py
  docs/snippets/technical-reference/pipeline/pipe_3.py
  docs/snippets/technical-reference/pipeline/pipeline_generator_2.py
  docs/snippets/technical-reference/pipeline/pipeline_generator_3.py
  docs/snippets/technical-reference/pipeline/pipeline_labeller_2.py
  docs/snippets/technical-reference/pipeline/pipeline_labeller_3.py
  docs/snippets/technical-reference/pipeline/pipeline_labeller_generator_1.py
  docs/snippets/technical-reference/pipeline/pipeline_labeller_generator_2.py
  docs/snippets/technical-reference/pipeline/pipeline_labeller_generator_3.py
  docs/snippets/technical-reference/pipeline/pipeline_llmpool_processllm_1.py
  docs/snippets/technical-reference/pipeline/pipeline_llmpool_processllm_2.py
  docs/snippets/technical-reference/pipeline/pipeline_llmpool_processllm_3.py
  docs/snippets/technical-reference/pipeline/pipeline_llmpool_processllm_4.py
  docs/snippets/technical-reference/pipeline/pipeline_llmpool_processllm_5.py
  docs/technical-reference/llms.md
  docs/technical-reference/pipeline.md
  docs/technical-reference/tasks.md
  examples/pipeline-preference-dataset-llmpool.py
  mkdocs.yml
  pyproject.toml
Labels: documentation

#190 Fix `PrometheusTask` could not be imported
  examples/pipeline-prometheus.py
  src/distilabel/tasks/__init__.py
  src/distilabel/tasks/critique/base.py
  src/distilabel/tasks/preference/base.py
  src/distilabel/tasks/preference/judgelm.py
  src/distilabel/tasks/preference/ultrafeedback.py
  src/distilabel/tasks/preference/ultrajudge.py
Labels: fix

#195 Fix `PrometheusTask` and `UltraCMTask` could not be chained with `TextGenerationTask`
  examples/pipeline-prometheus.py
  examples/pipeline-ultracm.py
  src/distilabel/tasks/critique/base.py
  src/distilabel/tasks/critique/prometheus.py
  src/distilabel/tasks/critique/ultracm.py
  src/distilabel/tasks/preference/base.py
  src/distilabel/tasks/preference/judgelm.py
  src/distilabel/tasks/preference/ultrafeedback.py
  src/distilabel/tasks/preference/ultrajudge.py
  src/distilabel/tasks/text_generation/base.py
  src/distilabel/tasks/text_generation/llama.py
  src/distilabel/tasks/text_generation/openai.py
  src/distilabel/tasks/text_generation/self_instruct.py
Labels: fix

#199 Update `generate_prompt` in `Task` subclasses to always return `Prompt`
  docs/snippets/technical-reference/llm/openai_generate.py
  docs/snippets/technical-reference/tasks/generic_llama2_textgeneration.py
  docs/snippets/technical-reference/tasks/generic_openai_textgeneration.py
  docs/technical-reference/tasks.md
  examples/inference-endpoints-llm-custom-task.py
  examples/pipeline-accelerate-and-openai.py
  examples/pipeline-fn-ultrafeedback.py
  examples/pipeline-pool-llm.py
  examples/pipeline-preference-dataset-llmpool.py
  src/distilabel/pipeline.py
  src/distilabel/tasks/__init__.py
  src/distilabel/tasks/base.py
  src/distilabel/tasks/critique/prometheus.py
  src/distilabel/tasks/critique/ultracm.py
  src/distilabel/tasks/text_generation/llama.py
  src/distilabel/tasks/text_generation/openai.py
Labels: fix, improvement

#200 Add `CritiqueTask` documentation
  docs/index.md
  docs/snippets/technical-reference/llm/transformers_generate.py
  docs/snippets/technical-reference/tasks/prometheus.py
  docs/snippets/technical-reference/tasks/ultracm.py
  docs/technical-reference/llms.md
  docs/technical-reference/pipeline.md
  docs/technical-reference/tasks.md
Labels: documentation

#201 Fix `UltraCMTask` scoring range and align `argilla` imports
  src/distilabel/tasks/base.py
  src/distilabel/tasks/critique/ultracm.py
  src/distilabel/tasks/text_generation/base.py
  src/distilabel/tasks/text_generation/self_instruct.py
Labels: fix
