Repository argilla-io/distilabel, pull requests merged in 2024-02, with the labels that each got.

#319 Add embedding tutorial to docs
  docs/tutorials/improving-text-embeddings-with-llms.ipynb
  mkdocs.yml
Labels: documentation, fix

#293 Add `MistralAILLM`
  .github/workflows/test.yml
  README.md
  docs/snippets/technical-reference/llm/mistralai_generate.py
  docs/technical-reference/llms.md
  pyproject.toml
  src/distilabel/llm/__init__.py
  src/distilabel/llm/mistralai.py
  src/distilabel/utils/imports.py
  tests/llm/test_mistralai.py
Labels: team: ml

#307 Use `ollama` Python client within `OllamaLLM`
  .github/workflows/test.yml
  README.md
  docs/index.md
  pyproject.toml
  src/distilabel/llm/ollama.py
  src/distilabel/utils/imports.py
  tests/llm/test_ollama.py
Labels: enhancement, integrations

#321 Add checkpoint strategy to automatically push to hub
  docs/snippets/technical-reference/pipeline/pipeline_dataset_checkpoint_4.py
  docs/technical-reference/pipeline.md
  src/distilabel/dataset.py
  src/distilabel/pipeline.py
  tests/test_dataset.py
Labels: enhancement

#341 Fix `CustomDataset.load_from_disk` with `str`/`Path` objects
  src/distilabel/dataset.py
  src/distilabel/utils/serialization.py
  tests/test_dataset.py
Labels: bug

#338 Add `Step` abstract class and new `Pipeline`
  pyproject.toml
  src/distilabel/pipeline/__init__.py
  src/distilabel/pipeline/_dag.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/step/__init__.py
  src/distilabel/step/base.py
  tests/pipeline/__init__.py
  tests/pipeline/conftest.py
  tests/pipeline/test_base.py
  tests/pipeline/test_dag.py
  tests/step/__init__.py
  tests/step/test_base.py
  tests/test_pipeline.py
Labels: enhancement

#344 Refactor _build_dataset piece for speed
  src/distilabel/pipeline.py
Labels: improvement

#346 Pipeline local execution
  pyproject.toml
  src/distilabel/pipeline/_dag.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/pipeline/step/__init__.py
  src/distilabel/pipeline/step/base.py
  src/distilabel/pipeline/step/generators/__init__.py
  src/distilabel/pipeline/step/generators/huggingface.py
  tests/pipeline/conftest.py
  tests/pipeline/step/__init__.py
  tests/pipeline/step/test_base.py
  tests/pipeline/test_base.py
  tests/pipeline/test_dag.py
  tests/pipeline/test_local.py
  tests/pipeline/utils.py
Labels: enhancement

#351 Fix Openai api error with OpenAI-compatible providers
  src/distilabel/llm/openai.py
Labels: fix

#353 Refactor `_BatchManager` to have list of batches per step
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  tests/pipeline/test_base.py
  tests/pipeline/test_local.py
Labels: enhancement

#355 Refactor getting parameters from `Step.process` method
  src/distilabel/pipeline/_dag.py
  src/distilabel/pipeline/step/base.py
Labels: enhancement, refactor

#354 Add `LLM`, `OpenAILLM`, `TransformersLLM`, and `LlamaCppLLM`
  src/distilabel/pipeline/llm/__init__.py
  src/distilabel/pipeline/llm/base.py
  src/distilabel/pipeline/llm/llamacpp.py
  src/distilabel/pipeline/llm/openai.py
  src/distilabel/pipeline/llm/transformers.py
  src/distilabel/pipeline/local.py
Labels: refactor

#356 Fix `Task` and `TextGeneration`
  src/distilabel/pipeline/step/task/base.py
  src/distilabel/pipeline/step/task/generation.py
Labels: fix

#358 Add `combine_dicts` function and `CombineColumns` class
  src/distilabel/pipeline/step/task/combine.py
  src/distilabel/pipeline/utils.py
Labels: enhancement

#349 Add serialization for the new components
  src/distilabel/pipeline/_dag.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/llm/base.py
  src/distilabel/pipeline/serialization.py
  src/distilabel/pipeline/step/base.py
  src/distilabel/utils/serialization_v2.py
  tests/integration/test_pipe_llms.py
  tests/integration/test_pipe_simple.py
  tests/pipeline/llm/test_serialization.py
  tests/pipeline/step/test_base.py
  tests/pipeline/test_base.py
  tests/pipeline/test_dag.py
Labels: enhancement, refactor

#359 Fix `OpenAILLM.api_key` due to `SecretStr` and `StepInput` wrong imports
  src/distilabel/pipeline/llm/openai.py
  tests/integration/test_pipe_llms.py
  tests/integration/test_pipe_simple.py
  tests/pipeline/llm/test_serialization.py
Labels: fix

#362 Add `GlobalStep`, fix `_BatchManager`, and add `logging`
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/llm/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/pipeline/logging.py
  src/distilabel/pipeline/step/base.py
  src/distilabel/pipeline/step/globals/__init__.py
  src/distilabel/pipeline/step/globals/huggingface.py
  src/distilabel/pipeline/step/task/generation.py
Labels: enhancement, fix

#361 Migrate vllm to the new API
  src/distilabel/pipeline/llm/base.py
  src/distilabel/pipeline/llm/llamacpp.py
  src/distilabel/pipeline/llm/openai.py
  src/distilabel/pipeline/llm/transformers.py
  src/distilabel/pipeline/llm/vllm.py
Labels: integrations

#364 Add fix for labels not returned by openai api
  src/distilabel/pipeline.py
Labels: fix

#366 Update `_BatchManager` to work with `GlobalStep`s and `input_batch_size` per step
  src/distilabel/pipeline/_dag.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/pipeline/step/base.py
  src/distilabel/utils/serialization_v2.py
  tests/pipeline/conftest.py
  tests/pipeline/llm/test_serialization.py
  tests/pipeline/step/test_base.py
  tests/pipeline/test_base.py
  tests/pipeline/utils.py
Labels: enhancement
