Repository argilla-io/distilabel, pull requests merged in 2024-06, with the labels that each got.

#680 Add `StructuredGeneration` task and support for `grammar` in `InferenceEndpointsLLM`
  docs/sections/pipeline_samples/examples/index.md
  src/distilabel/llms/anthropic.py
  src/distilabel/llms/base.py
  src/distilabel/llms/cohere.py
  src/distilabel/llms/groq.py
  src/distilabel/llms/huggingface/inference_endpoints.py
  src/distilabel/llms/huggingface/transformers.py
  src/distilabel/llms/litellm.py
  src/distilabel/llms/llamacpp.py
  src/distilabel/llms/mistral.py
  src/distilabel/llms/ollama.py
  src/distilabel/llms/openai.py
  src/distilabel/llms/vertexai.py
  src/distilabel/llms/vllm.py
  src/distilabel/pipeline/base.py
  src/distilabel/steps/tasks/__init__.py
  src/distilabel/steps/tasks/base.py
  src/distilabel/steps/tasks/structured_generation.py
  src/distilabel/steps/tasks/text_generation.py
  src/distilabel/steps/tasks/typing.py
  src/distilabel/utils/dicts.py
  tests/unit/llms/huggingface/test_inference_endpoints.py
  tests/unit/steps/tasks/test_structured_generation.py
  tests/unit/test_imports.py
Labels: enhancement, improvement, integrations

#696 Fix prepend batches
  src/distilabel/pipeline/base.py
  tests/unit/pipeline/test_base.py
Labels: fix

#691 [FEATURE] Include new `GeneratorStep` classes to load datasets from different formats
  src/distilabel/steps/__init__.py
  src/distilabel/steps/generators/huggingface.py
  tests/unit/steps/generators/sample_functions.jsonl
  tests/unit/steps/generators/test_data.py
  tests/unit/steps/generators/test_huggingface.py
  tests/unit/test_imports.py
Labels: enhancement, improvement

#712 Add citation readme
  README.md
Labels: documentation

#708 Move navigation to top bar
  docs/index.md
  docs/stylesheets/extra.css
  docs/stylesheets/fonts/FontAwesome.otf
  docs/stylesheets/fonts/fontawesome-webfont.eot
  docs/stylesheets/fonts/fontawesome-webfont.svg
  docs/stylesheets/fonts/fontawesome-webfont.ttf
  docs/stylesheets/fonts/fontawesome-webfont.woff
  docs/stylesheets/fonts/fontawesome-webfont.woff2
  mkdocs.yml
Labels: documentation

#713 Fix `install_dependencies.sh`
  scripts/install_dependencies.sh
Labels: fix

#706 Add context to guide the generate sentence pair task if informed
  src/distilabel/steps/tasks/sentence_transformers.py
  src/distilabel/steps/tasks/templates/generate-sentence-pair.jinja2
  tests/unit/steps/tasks/test_sentence_transformers.py
Labels: improvement

#714 Add examples to the LLMs to be shown in the components gallery
  src/distilabel/llms/anthropic.py
  src/distilabel/llms/anyscale.py
  src/distilabel/llms/azure.py
  src/distilabel/llms/cohere.py
  src/distilabel/llms/groq.py
  src/distilabel/llms/huggingface/transformers.py
  src/distilabel/llms/litellm.py
  src/distilabel/llms/llamacpp.py
  src/distilabel/llms/mistral.py
  src/distilabel/llms/openai.py
  src/distilabel/llms/together.py
  src/distilabel/llms/vllm.py
Labels: documentation

#707 Gather HF_TOKEN internally when calling `Distiset.push_to_hub` if token is None.
  src/distilabel/distiset.py
  src/distilabel/llms/huggingface/inference_endpoints.py
  src/distilabel/utils/huggingface.py
Labels: improvement

#683 Implement "Improving Text Embeddings with LLMs"
  src/distilabel/steps/tasks/__init__.py
  src/distilabel/steps/tasks/base.py
  src/distilabel/steps/tasks/improving_text_embeddings.py
  src/distilabel/steps/tasks/templates/improving_text_embeddings/bitext-retrieval.jinja2
  src/distilabel/steps/tasks/templates/improving_text_embeddings/brainstorming/text-classification.jinja2
  src/distilabel/steps/tasks/templates/improving_text_embeddings/brainstorming/text-matching-long.jinja2
  src/distilabel/steps/tasks/templates/improving_text_embeddings/brainstorming/text-matching-short.jinja2
  src/distilabel/steps/tasks/templates/improving_text_embeddings/brainstorming/text-retrieval.jinja2
  src/distilabel/steps/tasks/templates/improving_text_embeddings/long-text-matching.jinja2
  src/distilabel/steps/tasks/templates/improving_text_embeddings/monolingual-triplet.jinja2
  src/distilabel/steps/tasks/templates/improving_text_embeddings/short-text-matching.jinja2
  src/distilabel/steps/tasks/templates/improving_text_embeddings/text-classification.jinja2
  src/distilabel/steps/tasks/templates/improving_text_embeddings/text-retrieval.jinja2
  tests/unit/steps/tasks/test_improving_text_embeddings.py
  tests/unit/test_imports.py
Labels: integrations

#670 Add `ArenaHard` benchmark and `ArenaHardResults` step
  pyproject.toml
  scripts/install_dependencies.sh
  src/distilabel/steps/generators/huggingface.py
  src/distilabel/steps/tasks/__init__.py
  src/distilabel/steps/tasks/benchmarks/__init__.py
  src/distilabel/steps/tasks/benchmarks/arena_hard.py
  src/distilabel/steps/tasks/text_generation.py
  tests/unit/steps/tasks/benchmarks/__init__.py
  tests/unit/steps/tasks/benchmarks/test_arena_hard.py
  tests/unit/test_imports.py
Labels: integrations, benchmark

#704 Refactor `Pipeline` and `BasePipeline` classes
  pyproject.toml
  src/distilabel/llms/base.py
  src/distilabel/llms/huggingface/transformers.py
  src/distilabel/llms/mixins.py
  src/distilabel/llms/vllm.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/batch.py
  src/distilabel/pipeline/batch_manager.py
  src/distilabel/pipeline/constants.py
  src/distilabel/pipeline/local.py
  src/distilabel/pipeline/routing_batch_function.py
  src/distilabel/pipeline/typing.py
  src/distilabel/pipeline/write_buffer.py
  src/distilabel/steps/base.py
  src/distilabel/steps/tasks/base.py
  src/distilabel/utils/serialization.py
  tests/unit/llms/test_mixins.py
  tests/unit/pipeline/test_base.py
  tests/unit/pipeline/test_batch.py
  tests/unit/pipeline/test_batch_manager.py
  tests/unit/pipeline/test_local.py
  tests/unit/pipeline/test_routing_batch_function.py
  tests/unit/pipeline/test_write_buffer.py
  tests/unit/pipeline/utils.py
Labels: enhancement, refactor

#725 Fix AzureOpenAILLM load method setting the correct path to mock the internal class
  src/distilabel/llms/azure.py
Labels: fix

#715 Components examples steps
  docs/stylesheets/extra.css
  src/distilabel/steps/argilla/preference.py
  src/distilabel/steps/argilla/text_generation.py
  src/distilabel/steps/combine.py
  src/distilabel/steps/deita.py
  src/distilabel/steps/expand.py
  src/distilabel/steps/formatting/conversation.py
  src/distilabel/steps/formatting/dpo.py
  src/distilabel/steps/formatting/sft.py
  src/distilabel/steps/generators/data.py
  src/distilabel/steps/generators/huggingface.py
  src/distilabel/steps/globals/huggingface.py
  src/distilabel/steps/keep.py
Labels: documentation

#724 Add examples for tasks in the components gallery
  src/distilabel/steps/tasks/complexity_scorer.py
  src/distilabel/steps/tasks/evol_instruct/base.py
  src/distilabel/steps/tasks/evol_instruct/evol_complexity/base.py
  src/distilabel/steps/tasks/evol_instruct/evol_complexity/generator.py
  src/distilabel/steps/tasks/evol_instruct/generator.py
  src/distilabel/steps/tasks/evol_quality/base.py
  src/distilabel/steps/tasks/generate_embeddings.py
  src/distilabel/steps/tasks/genstruct.py
  src/distilabel/steps/tasks/pair_rm.py
  src/distilabel/steps/tasks/prometheus_eval.py
  src/distilabel/steps/tasks/quality_scorer.py
  src/distilabel/steps/tasks/self_instruct.py
  src/distilabel/steps/tasks/structured_generation.py
  src/distilabel/steps/tasks/text_generation.py
  src/distilabel/steps/tasks/ultrafeedback.py
Labels: documentation

#688 [FEATURE] Refactor of structured generation and use schemas defined in a dataset
  src/distilabel/llms/anthropic.py
  src/distilabel/llms/base.py
  src/distilabel/llms/cohere.py
  src/distilabel/llms/groq.py
  src/distilabel/llms/huggingface/inference_endpoints.py
  src/distilabel/llms/huggingface/transformers.py
  src/distilabel/llms/litellm.py
  src/distilabel/llms/llamacpp.py
  src/distilabel/llms/mistral.py
  src/distilabel/llms/ollama.py
  src/distilabel/llms/openai.py
  src/distilabel/llms/vllm.py
  src/distilabel/steps/tasks/structured_generation.py
  src/distilabel/steps/tasks/structured_outputs/instructor.py
  src/distilabel/steps/tasks/structured_outputs/outlines.py
  src/distilabel/steps/tasks/typing.py
  tests/unit/llms/huggingface/test_inference_endpoints.py
  tests/unit/llms/test_llamacpp.py
  tests/unit/llms/test_vertexai.py
  tests/unit/llms/test_vllm.py
  tests/unit/steps/tasks/evol_instruct/test_base.py
  tests/unit/steps/tasks/evol_instruct/test_generator.py
  tests/unit/steps/tasks/evol_quality/test_base.py
  tests/unit/steps/tasks/structured_outputs/test_outlines.py
  tests/unit/steps/tasks/test_base.py
  tests/unit/steps/tasks/test_structured_generation.py
Labels: enhancement, refactor

#735 Add `MixtureOfAgentsLLM`
  docs/sections/how_to_guides/advanced/structured_generation.md
  src/distilabel/cli/pipeline/utils.py
  src/distilabel/llms/__init__.py
  src/distilabel/llms/anthropic.py
  src/distilabel/llms/anyscale.py
  src/distilabel/llms/azure.py
  src/distilabel/llms/base.py
  src/distilabel/llms/cohere.py
  src/distilabel/llms/groq.py
  src/distilabel/llms/huggingface/inference_endpoints.py
  src/distilabel/llms/litellm.py
  src/distilabel/llms/mistral.py
  src/distilabel/llms/moa.py
  src/distilabel/llms/ollama.py
  src/distilabel/llms/openai.py
  src/distilabel/llms/together.py
  src/distilabel/llms/vertexai.py
  src/distilabel/mixins/runtime_parameters.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/typing.py
  src/distilabel/steps/base.py
  src/distilabel/steps/tasks/base.py
  src/distilabel/steps/tasks/benchmarks/arena_hard.py
  src/distilabel/steps/tasks/structured_outputs/instructor.py
  src/distilabel/steps/tasks/text_generation.py
  src/distilabel/utils/itertools.py
  src/distilabel/utils/mkdocs/templates/components-gallery/llm-detail.jinja2
  src/distilabel/utils/serialization.py
  tests/unit/conftest.py
  tests/unit/llms/test_cohere.py
  tests/unit/llms/test_moa.py
  tests/unit/mixins/test_runtime_parameters.py
  tests/unit/steps/tasks/benchmarks/test_arena_hard.py
  tests/unit/steps/tasks/conftest.py
  tests/unit/steps/tasks/test_base.py
  tests/unit/steps/tasks/test_complexity_scorer.py
  tests/unit/steps/tasks/test_genstruct.py
  tests/unit/steps/tasks/test_prometheus_eval.py
  tests/unit/steps/tasks/test_quality_scorer.py
  tests/unit/steps/tasks/test_self_instruct.py
  tests/unit/steps/tasks/test_sentence_transformers.py
  tests/unit/steps/tasks/test_text_generation.py
  tests/unit/steps/test_base.py
  tests/unit/utils/test_serialization.py
Labels: enhancement

#741 Add `examples/arena_hard.py` and remove from `distilabel` core
  docs/sections/pipeline_samples/examples/index.md
  examples/arena_hard.py
  pyproject.toml
  scripts/install_dependencies.sh
  src/distilabel/steps/tasks/__init__.py
  src/distilabel/steps/tasks/benchmarks/__init__.py
  tests/unit/steps/tasks/benchmarks/__init__.py
  tests/unit/steps/tasks/benchmarks/test_arena_hard.py
  tests/unit/test_imports.py
Labels: example

#742 Add serving LLM section in the docs
  docs/sections/getting_started/faq.md
  docs/sections/how_to_guides/advanced/argilla.md
  docs/sections/how_to_guides/advanced/serving_an_llm_for_reuse.md
  mkdocs.yml
Labels: documentation

#745 Fix docs for distiset.save_to_disk kwargs
  src/distilabel/distiset.py
Labels: documentation, example

#747 Add new step `CombineKeys`
  src/distilabel/pipeline/utils.py
  src/distilabel/steps/__init__.py
  src/distilabel/steps/combine.py
  tests/unit/steps/test_combine.py
  tests/unit/test_imports.py
Labels: documentation, enhancement

#720 Add `requirements` list for `Pipeline`
  docs/api/step_gallery/columns.md
  docs/sections/how_to_guides/advanced/pipeline_requirements.md
  docs/sections/how_to_guides/index.md
  mkdocs.yml
  src/distilabel/mixins/requirements.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/utils.py
  src/distilabel/steps/base.py
  src/distilabel/utils/requirements.py
  tests/unit/pipeline/test_base.py
  tests/unit/utils/test_requirements.py
Labels: enhancement

#750 Add `StepResources` and step replicas in `Pipeline`
  docs/api/step/resources.md
  docs/sections/how_to_guides/advanced/assigning_resources_to_step.md
  docs/sections/how_to_guides/advanced/structured_generation.md
  docs/sections/pipeline_samples/examples/index.md
  mkdocs.yml
  src/distilabel/pipeline/_dag.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/batch_manager.py
  src/distilabel/pipeline/local.py
  src/distilabel/steps/__init__.py
  src/distilabel/steps/base.py
  src/distilabel/steps/constants.py
  tests/integration/test_multiple_replicas.py
  tests/unit/pipeline/test_base.py
  tests/unit/pipeline/test_batch_manager.py
  tests/unit/pipeline/test_dag.py
  tests/unit/pipeline/test_local.py
  tests/unit/steps/argilla/test_base.py
  tests/unit/steps/argilla/test_preference.py
  tests/unit/steps/argilla/test_text_generation.py
  tests/unit/steps/tasks/evol_instruct/test_base.py
  tests/unit/steps/tasks/evol_instruct/test_generator.py
  tests/unit/steps/tasks/evol_quality/test_base.py
  tests/unit/steps/tasks/test_base.py
  tests/unit/steps/tasks/test_pair_rm.py
  tests/unit/steps/test_base.py
  tests/unit/steps/test_decorator.py
  tests/unit/test_imports.py
Labels: enhancement
