Repository argilla-io/distilabel, pull requests merged in 2024-07, with the labels that each got.

#764 Fix `response_format` for `TogetherLLM` and `AnyScaleLLM`
  src/distilabel/llms/openai.py
Labels: fix

#760 Add load stages
  docs/api/mixins/requirements.md
  docs/api/mixins/runtime_parameters.md
  docs/sections/how_to_guides/advanced/assigning_resources_to_step.md
  mkdocs.yml
  src/distilabel/pipeline/_dag.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/batch_manager.py
  src/distilabel/pipeline/local.py
  src/distilabel/utils/logging.py
  tests/integration/test_load_stages.py
  tests/integration/test_routing_batch_function.py
  tests/unit/pipeline/test_base.py
  tests/unit/pipeline/test_batch_manager.py
  tests/unit/pipeline/test_dag.py
  tests/unit/pipeline/test_local.py
  tests/unit/pipeline/utils.py
Labels: enhancement

#770 Update min required version to `python==3.9`
  .github/workflows/test.yml
  README.md
  docs/sections/getting_started/installation.md
  pyproject.toml
  scripts/install_dependencies.sh
  src/distilabel/pipeline/local.py
  tests/unit/llms/huggingface/test_inference_endpoints.py
  tests/unit/pipeline/test_base.py
Labels: dependencies

#762 Optionally include the pipeline script in the hub when pushing your distiset
  docs/sections/how_to_guides/advanced/cli/index.md
  docs/sections/how_to_guides/advanced/distiset.md
  src/distilabel/cli/pipeline/app.py
  src/distilabel/cli/pipeline/utils.py
  src/distilabel/distiset.py
  src/distilabel/utils/card/distilabel_template.md
Labels: improvement

#774 Add `docs-pr.yml` and `docs-pr-close.yml` workflows
  .github/workflows/docs-pr-close.yml
  .github/workflows/docs-pr.yml
  .github/workflows/docs.yml
  docs/scripts/gen_popular_issues.py
Labels: documentation

#781 Fix passing `input` to `format_output` function
  src/distilabel/steps/tasks/base.py
  tests/unit/steps/tasks/test_base.py
Labels: fix

#778 Add `Magpie` and `MagpieGenerator` tasks
  pyproject.toml
  src/distilabel/llms/__init__.py
  src/distilabel/llms/azure.py
  src/distilabel/llms/base.py
  src/distilabel/llms/huggingface/inference_endpoints.py
  src/distilabel/llms/huggingface/transformers.py
  src/distilabel/llms/mixins/__init__.py
  src/distilabel/llms/mixins/cuda_device_placement.py
  src/distilabel/llms/mixins/magpie.py
  src/distilabel/llms/vllm.py
  src/distilabel/pipeline/step_wrapper.py
  src/distilabel/steps/tasks/__init__.py
  src/distilabel/steps/tasks/evol_instruct/generator.py
  src/distilabel/steps/tasks/magpie/__init__.py
  src/distilabel/steps/tasks/magpie/base.py
  src/distilabel/steps/tasks/magpie/generator.py
  src/distilabel/steps/tasks/typing.py
  src/distilabel/utils/itertools.py
  tests/unit/conftest.py
  tests/unit/llms/huggingface/test_inference_endpoints.py
  tests/unit/llms/mixins/__init__.py
  tests/unit/llms/mixins/test_cuda_device_placement.py
  tests/unit/llms/mixins/test_magpie.py
  tests/unit/llms/test_groq.py
  tests/unit/steps/tasks/magpie/__init__.py
  tests/unit/steps/tasks/magpie/test_base.py
  tests/unit/steps/tasks/magpie/test_generator.py
  tests/unit/steps/tasks/structured_outputs/test_outlines.py
Labels: enhancement

#783 Fix some issues related to `Magpie` task
  src/distilabel/steps/tasks/magpie/base.py
  src/distilabel/steps/tasks/magpie/generator.py
  tests/unit/steps/tasks/magpie/test_base.py
  tests/unit/steps/tasks/magpie/test_generator.py
Labels: fix

#786 Fix Import Error for KeepColumns in instruction_backtranslation.md (Issue #785)
  docs/sections/pipeline_samples/papers/instruction_backtranslation.md
Labels: documentation

#791 Correct variable name in dataset push example (in ultrafeedback.md file) (Issue #787)
  docs/sections/pipeline_samples/papers/ultrafeedback.md
Labels: documentation

#784 Add `end_with_user` and `include_system_prompt` flags to `Magpie` tasks and handle `None`s.
  src/distilabel/steps/tasks/magpie/base.py
  src/distilabel/steps/tasks/magpie/generator.py
  tests/unit/llms/huggingface/test_inference_endpoints.py
  tests/unit/steps/tasks/magpie/test_base.py
  tests/unit/steps/tasks/magpie/test_generator.py
Labels: enhancement

#796 Add workflow concurrency group for publishing docs
  .github/workflows/docs-pr-close.yml
  .github/workflows/docs-pr.yml
  .github/workflows/docs.yml
Labels: documentation, fix, ci

#795 Add `_desired_num_gpus` attribute to `CudaDevicePlacementMixin`
  src/distilabel/llms/mixins/cuda_device_placement.py
  src/distilabel/pipeline/step_wrapper.py
  tests/unit/llms/mixins/test_cuda_device_placement.py
Labels: enhancement

#805 Compatibility with `vLLM` with `tensor_parallel_size` argument
  docs/sections/how_to_guides/advanced/scaling_with_ray.md
  pyproject.toml
  src/distilabel/llms/huggingface/inference_endpoints.py
  src/distilabel/pipeline/local.py
Labels: enhancement

#808 Update default names in `GroupColumns`
  src/distilabel/steps/columns/group.py
  tests/integration/test_branching_missaligmnent.py
  tests/unit/steps/columns/test_group.py
Labels: improvement

#815 Update `InferenceEndpointsLLM` to use `chat_completion` method
  pyproject.toml
  src/distilabel/llms/huggingface/inference_endpoints.py
  tests/unit/llms/huggingface/test_inference_endpoints.py
Labels: enhancement

#809 Add default name for a pipeline
  src/distilabel/pipeline/base.py
  tests/unit/pipeline/test_base.py
Labels: improvement

#833 Some more `Magpie` improvements
  src/distilabel/steps/tasks/magpie/base.py
  src/distilabel/steps/tasks/magpie/generator.py
  tests/unit/steps/tasks/magpie/test_base.py
  tests/unit/steps/tasks/magpie/test_generator.py
Labels: enhancement

#830 Add `Embeddings` base class, `SentenceTransformerEmbeddings` class, `EmbeddingGeneration` and `FaissNearestNeighbour` steps
  pyproject.toml
  scripts/install_dependencies.sh
  src/distilabel/embeddings/__init__.py
  src/distilabel/embeddings/base.py
  src/distilabel/embeddings/sentence_transformers.py
  src/distilabel/llms/base.py
  src/distilabel/llms/huggingface/transformers.py
  src/distilabel/steps/__init__.py
  src/distilabel/steps/embeddings/__init__.py
  src/distilabel/steps/embeddings/embedding_generation.py
  src/distilabel/steps/embeddings/nearest_neighbour.py
  src/distilabel/utils/export_components_info.py
  src/distilabel/utils/logging.py
  src/distilabel/utils/mkdocs/components_gallery.py
  src/distilabel/utils/mkdocs/templates/components-gallery/index.md
  tests/unit/embeddings/__init__.py
  tests/unit/embeddings/test_sentence_transformers.py
  tests/unit/steps/embeddings/__init__.py
  tests/unit/steps/embeddings/test_embedding_generation.py
  tests/unit/steps/embeddings/test_nearest_neighbour.py
Labels: enhancement

#814 Create file per hostname in `CudaDevicePlacementMixin`
  src/distilabel/llms/mixins/cuda_device_placement.py
  src/distilabel/pipeline/local.py
  src/distilabel/pipeline/ray.py
  src/distilabel/pipeline/step_wrapper.py
  tests/unit/pipeline/test_local.py
  tests/unit/steps/tasks/structured_outputs/test_outlines.py
Labels: fix

#812 Create a `GeneratorStep` from a dataset using a helper function
  docs/api/step/generator_step.md
  docs/sections/getting_started/quickstart.md
  docs/sections/how_to_guides/basic/pipeline/index.md
  src/distilabel/pipeline/_dag.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/pipeline/ray.py
  src/distilabel/pipeline/typing.py
  src/distilabel/steps/__init__.py
  src/distilabel/steps/generators/huggingface.py
  src/distilabel/steps/generators/utils.py
  tests/integration/test_dataset_without_step.py
  tests/unit/pipeline/test_base.py
  tests/unit/steps/generators/test_utils.py
Labels: enhancement

#838 Do not take into account `disable_cuda_device_placement` for pipeline signature
  src/distilabel/pipeline/base.py
  tests/unit/pipeline/test_base.py
Labels: fix

#841 Fix `LoadDataFromHub` attribute `_dataset` had `ellipsis` by default instead of `None`
  src/distilabel/steps/generators/huggingface.py
Labels: fix

#842 Create `PlacementGroup` for steps using `vLLM`
  docs/sections/how_to_guides/advanced/scaling_with_ray.md
  src/distilabel/pipeline/ray.py
Labels: enhancement

#845 Use `CudaDevicePlacementMixin` in `RewardModelScore` step
  src/distilabel/embeddings/base.py
  src/distilabel/llms/base.py
  src/distilabel/llms/mixins/cuda_device_placement.py
  src/distilabel/pipeline/step_wrapper.py
  src/distilabel/steps/reward_model.py
Labels: enhancement
