Repository argilla-io/distilabel, pull requests merged in 2024-08, with the labels that each got.

#850 Fix typo in docs
  docs/sections/pipeline_samples/papers/ultrafeedback.md
Labels: documentation

#851 Fix creating placement group when `pipeline_parallel_size>1`
  src/distilabel/pipeline/ray.py
Labels: fix

#854 Add `ClientvLLM` class
  src/distilabel/llms/__init__.py
  src/distilabel/llms/openai.py
  src/distilabel/llms/vllm.py
  tests/unit/llms/test_vllm.py
Labels: enhancement

#856 Add hard-negative flag to include similar challenging negatives on triplets
  src/distilabel/steps/tasks/sentence_transformers.py
  tests/unit/steps/tasks/test_sentence_transformers.py
Labels: improvement

#855 Add bibtex references in the docstrings to be shown in the README
  docs/sections/how_to_guides/advanced/distiset.md
  src/distilabel/distiset.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/pipeline/ray.py
  src/distilabel/steps/deita.py
  src/distilabel/steps/embeddings/nearest_neighbour.py
  src/distilabel/steps/tasks/complexity_scorer.py
  src/distilabel/steps/tasks/evol_instruct/base.py
  src/distilabel/steps/tasks/evol_instruct/evol_complexity/base.py
  src/distilabel/steps/tasks/evol_instruct/evol_complexity/generator.py
  src/distilabel/steps/tasks/evol_instruct/generator.py
  src/distilabel/steps/tasks/evol_quality/base.py
  src/distilabel/steps/tasks/generate_embeddings.py
  src/distilabel/steps/tasks/genstruct.py
  src/distilabel/steps/tasks/improving_text_embeddings.py
  src/distilabel/steps/tasks/instruction_backtranslation.py
  src/distilabel/steps/tasks/magpie/base.py
  src/distilabel/steps/tasks/magpie/generator.py
  src/distilabel/steps/tasks/pair_rm.py
  src/distilabel/steps/tasks/prometheus_eval.py
  src/distilabel/steps/tasks/quality_scorer.py
  src/distilabel/steps/tasks/self_instruct.py
  src/distilabel/steps/tasks/ultrafeedback.py
  src/distilabel/utils/card/distilabel_template.md
  src/distilabel/utils/docstring.py
  tests/unit/utils/test_docstring.py
Labels: documentation, enhancement

#861 Create new `distilabel.constants` module to store constants and avoid circular imports
  src/distilabel/__init__.py
  src/distilabel/cli/pipeline/utils.py
  src/distilabel/constants.py
  src/distilabel/distiset.py
  src/distilabel/pipeline/_dag.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/batch_manager.py
  src/distilabel/pipeline/ray.py
  src/distilabel/pipeline/step_wrapper.py
  src/distilabel/steps/tasks/base.py
Labels: fix

#862 Make `ClientvLLM.model_name` a `cached_property`
  src/distilabel/llms/vllm.py
  tests/unit/llms/test_vllm.py
Labels: enhancement, fix

#863 Pass dataset to dry_run method
  src/distilabel/pipeline/base.py
Labels: fix

#868 Add default structured output for `GenerateSentencePair` task
  src/distilabel/steps/tasks/base.py
  src/distilabel/steps/tasks/sentence_transformers.py
  tests/unit/conftest.py
  tests/unit/steps/tasks/test_sentence_transformers.py
Labels: enhancement

#873 Quality scorer default structured output
  src/distilabel/steps/tasks/quality_scorer.py
  tests/unit/steps/tasks/test_quality_scorer.py
Labels: enhancement

#876 Ultrafeedback default structured output
  src/distilabel/steps/tasks/ultrafeedback.py
  tests/unit/steps/tasks/test_ultrafeedback.py
Labels: enhancement

#888 Remove use of `default_chat_template`
  src/distilabel/llms/chat_templates.py
  src/distilabel/llms/huggingface/transformers.py
  src/distilabel/llms/vllm.py
Labels: fix

#891 Fix unit tests after release of `transformers==4.44.0`
  src/distilabel/llms/huggingface/transformers.py
  tests/unit/llms/huggingface/test_inference_endpoints.py
  tests/unit/llms/huggingface/test_transformers.py
  tests/unit/llms/test_vllm.py
  tests/unit/steps/tasks/structured_outputs/test_outlines.py
  tests/unit/steps/tasks/test_generate_embeddings.py
  tests/unit/steps/test_reward_model.py
Labels: fix

#892 Fix default structured output
  src/distilabel/steps/tasks/base.py
  tests/unit/steps/tasks/evol_instruct/test_base.py
  tests/unit/steps/tasks/evol_instruct/test_generator.py
  tests/unit/steps/tasks/evol_quality/test_base.py
  tests/unit/steps/tasks/magpie/test_base.py
  tests/unit/steps/tasks/magpie/test_generator.py
  tests/unit/steps/tasks/test_base.py
Labels: fix, improvement

#898 Exclude `repo_id` from `LoadDataFromFileSystem`
  src/distilabel/steps/generators/huggingface.py
  tests/unit/steps/generators/test_huggingface.py
Labels: fix

#877 Fix loader to read from a glob pattern
  src/distilabel/steps/generators/huggingface.py
  tests/unit/steps/generators/test_huggingface.py
Labels: improvement

#733 Deepseek prover task
  docs/assets/tutorials-assets/deepseek_prover.png
  docs/sections/pipeline_samples/papers/deepseek_prover.md
  examples/deepseek_prover.py
  mkdocs.yml
Labels: documentation, example, tutorial

#903 Add new `add_raw_input` argument to `_Task` so we can automatically include the formatted input
  docs/sections/how_to_guides/basic/task/index.md
  src/distilabel/steps/tasks/base.py
  tests/unit/steps/tasks/evol_instruct/test_base.py
  tests/unit/steps/tasks/evol_instruct/test_generator.py
  tests/unit/steps/tasks/evol_quality/test_base.py
  tests/unit/steps/tasks/magpie/test_base.py
  tests/unit/steps/tasks/magpie/test_generator.py
  tests/unit/steps/tasks/test_base.py
  tests/unit/steps/tasks/test_improving_text_embeddings.py
  tests/unit/steps/tasks/test_instruction_backtranslation.py
  tests/unit/steps/tasks/test_structured_generation.py
  tests/unit/steps/tasks/test_text_generation.py
  tests/unit/steps/tasks/test_ultrafeedback.py
Labels: enhancement

#902 New `TruncateTextColumn` to truncate the length of texts using the number of tokens or characters
  src/distilabel/steps/__init__.py
  src/distilabel/steps/truncate.py
  src/distilabel/utils/mkdocs/components_gallery.py
  tests/unit/steps/test_truncate.py
Labels: enhancement

#883 Update `inputs` and `outputs` interface to allow returning dict indicating optionality
  docs/sections/how_to_guides/basic/step/generator_step.md
  docs/sections/how_to_guides/basic/step/global_step.md
  docs/sections/how_to_guides/basic/step/index.md
  docs/sections/how_to_guides/basic/task/index.md
  src/distilabel/pipeline/_dag.py
  src/distilabel/steps/argilla/base.py
  src/distilabel/steps/base.py
  src/distilabel/steps/columns/expand.py
  src/distilabel/steps/columns/group.py
  src/distilabel/steps/columns/keep.py
  src/distilabel/steps/columns/merge.py
  src/distilabel/steps/decorator.py
  src/distilabel/steps/embeddings/embedding_generation.py
  src/distilabel/steps/formatting/conversation.py
  src/distilabel/steps/formatting/dpo.py
  src/distilabel/steps/formatting/sft.py
  src/distilabel/steps/reward_model.py
  src/distilabel/steps/tasks/generate_embeddings.py
  src/distilabel/steps/tasks/improving_text_embeddings.py
  src/distilabel/steps/tasks/magpie/base.py
  src/distilabel/steps/tasks/magpie/generator.py
  src/distilabel/steps/tasks/pair_rm.py
  src/distilabel/steps/typing.py
  tests/unit/steps/test_base.py
Labels: enhancement

#904 Update mistrallm
  pyproject.toml
  src/distilabel/llms/mistral.py
  tests/unit/llms/test_mistral.py
Labels: improvement

#893 Add tutorial - generate data for training embeddings and reranking models
  docs/sections/how_to_guides/advanced/structured_generation.md
  docs/sections/pipeline_samples/examples/benchmarking_with_distilabel.md
  docs/sections/pipeline_samples/examples/index.md
  docs/sections/pipeline_samples/examples/llama_cpp_with_outlines.md
  docs/sections/pipeline_samples/examples/mistralai_with_instructor.md
  docs/sections/pipeline_samples/papers/deita.md
  docs/sections/pipeline_samples/papers/index.md
  docs/sections/pipeline_samples/papers/instruction_backtranslation.md
  docs/sections/pipeline_samples/papers/prometheus.md
  docs/sections/pipeline_samples/papers/ultrafeedback.md
  docs/sections/pipeline_samples/tutorials/GenerateSentencePair.ipynb
  mkdocs.yml
  src/distilabel/llms/vllm.py
Labels: documentation

#910 Fix load data from disk
  src/distilabel/steps/generators/huggingface.py
  tests/unit/steps/generators/test_huggingface.py
Labels: fix

#919 Do not cancel in progress docs workflows
  .github/workflows/docs-pr-close.yml
  .github/workflows/docs-pr.yml
  .github/workflows/docs.yml
Labels: documentation, ci

#921 Add `URIAL` task
  src/distilabel/steps/tasks/__init__.py
  src/distilabel/steps/tasks/templates/urial.jinja2
  src/distilabel/steps/tasks/text_generation.py
  src/distilabel/steps/tasks/ultrafeedback.py
  src/distilabel/steps/tasks/urial.py
  tests/unit/steps/tasks/test_text_generation.py
  tests/unit/steps/tasks/test_urial.py
Labels: enhancement

#920 Add `vLLMEmbeddings`
  src/distilabel/embeddings/__init__.py
  src/distilabel/embeddings/vllm.py
  tests/unit/embeddings/test_vllm.py
Labels: enhancement

#912 Fix `StructuredGeneration` examples and internal check
  src/distilabel/llms/base.py
  src/distilabel/steps/tasks/structured_generation.py
  src/distilabel/steps/tasks/structured_outputs/outlines.py
Labels: fix, improvement

#878 Generate deterministic pipeline name when it's not given
  src/distilabel/pipeline/base.py
  tests/unit/pipeline/test_base.py
Labels: fix

#911 Add custom errors
  docs/api/pipeline/step_wrapper.md
  docs/sections/how_to_guides/basic/step/index.md
  mkdocs.yml
  src/distilabel/cli/pipeline/utils.py
  src/distilabel/constants.py
  src/distilabel/errors.py
  src/distilabel/llms/base.py
  src/distilabel/pipeline/_dag.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/routing_batch_function.py
  src/distilabel/pipeline/step_wrapper.py
  src/distilabel/pipeline/utils.py
  src/distilabel/steps/argilla/base.py
  src/distilabel/steps/argilla/preference.py
  src/distilabel/steps/argilla/text_generation.py
  src/distilabel/steps/base.py
  src/distilabel/steps/generators/huggingface.py
  src/distilabel/steps/generators/utils.py
  src/distilabel/steps/tasks/generate_embeddings.py
  src/distilabel/steps/tasks/magpie/base.py
  src/distilabel/steps/tasks/magpie/generator.py
  src/distilabel/steps/tasks/prometheus_eval.py
  src/distilabel/steps/tasks/structured_generation.py
  src/distilabel/steps/tasks/structured_outputs/instructor.py
  src/distilabel/steps/tasks/structured_outputs/outlines.py
  src/distilabel/steps/tasks/text_generation.py
  src/distilabel/utils/docstring.py
  tests/unit/test_errors.py
Labels: enhancement

#924 Fix passing `base_url` in `model_id` in `InferenceEndpointsLLM`
  Makefile
  pyproject.toml
  scripts/install_dependencies.sh
  src/distilabel/llms/huggingface/inference_endpoints.py
  src/distilabel/llms/vllm.py
  tests/conftest.py
  tests/integration/test_ray_pipeline.py
  tests/unit/pipeline/test_ray.py
Labels: fix

#928 Add `revision` runtime parameter to `LoadDataFromHub`
  src/distilabel/steps/generators/huggingface.py
  tests/integration/test_multiple_replicas.py
  tests/unit/steps/tasks/test_pair_rm.py
  tests/unit/steps/tasks/test_ultrafeedback.py
  tests/unit/steps/tasks/test_urial.py
  tests/unit/steps/test_truncate.py
Labels: enhancement

#931 Add minhash related steps to deduplicate texts
  pyproject.toml
  scripts/install_dependencies.sh
  src/distilabel/steps/__init__.py
  src/distilabel/steps/filtering/__init__.py
  src/distilabel/steps/filtering/_datasketch.py
  src/distilabel/steps/filtering/minhash.py
  tests/integration/test_deduplication.py
  tests/unit/steps/test_filtering/__init__.py
  tests/unit/steps/test_filtering/test_minhash.py
Labels: enhancement
