Repository argilla-io/distilabel, pull requests merged in 2024-11, with the labels that each got.

#1051 Fix a tiny typo in `_Step` docstring
  src/distilabel/steps/base.py
Labels: documentation

#1050 docs: improve docs for `MinHashDedup` `Step`
  src/distilabel/steps/filtering/_datasketch.py
  src/distilabel/steps/filtering/minhash.py
Labels: documentation

#1053 Fix new response_format variable in openai api
  src/distilabel/models/llms/openai.py
Labels: fix

#1034 Update `LLM.generate` output to include `statistics`
  docs/sections/how_to_guides/basic/llm/index.md
  docs/sections/how_to_guides/basic/task/index.md
  src/distilabel/models/llms/anthropic.py
  src/distilabel/models/llms/base.py
  src/distilabel/models/llms/cohere.py
  src/distilabel/models/llms/groq.py
  src/distilabel/models/llms/huggingface/inference_endpoints.py
  src/distilabel/models/llms/huggingface/transformers.py
  src/distilabel/models/llms/litellm.py
  src/distilabel/models/llms/llamacpp.py
  src/distilabel/models/llms/mistral.py
  src/distilabel/models/llms/ollama.py
  src/distilabel/models/llms/openai.py
  src/distilabel/models/llms/typing.py
  src/distilabel/models/llms/utils.py
  src/distilabel/models/llms/vertexai.py
  src/distilabel/models/llms/vllm.py
  src/distilabel/steps/tasks/base.py
  src/distilabel/steps/tasks/evol_instruct/base.py
  src/distilabel/steps/tasks/evol_instruct/generator.py
  src/distilabel/steps/tasks/evol_quality/base.py
  src/distilabel/steps/tasks/magpie/base.py
  src/distilabel/steps/typing.py
  src/distilabel/utils/dicts.py
  tests/integration/test_offline_batch_generation.py
  tests/unit/conftest.py
  tests/unit/models/llms/huggingface/test_inference_endpoints.py
  tests/unit/models/llms/huggingface/test_transformers.py
  tests/unit/models/llms/test_anthropic.py
  tests/unit/models/llms/test_cohere.py
  tests/unit/models/llms/test_groq.py
  tests/unit/models/llms/test_litellm.py
  tests/unit/models/llms/test_llamacpp.py
  tests/unit/models/llms/test_mistral.py
  tests/unit/models/llms/test_ollama.py
  tests/unit/models/llms/test_openai.py
  tests/unit/models/llms/test_vertexai.py
  tests/unit/models/llms/test_vllm.py
  tests/unit/models/llms/utils.py
  tests/unit/steps/clustering/test_text_clustering.py
  tests/unit/steps/tasks/apigen/test_generator.py
  tests/unit/steps/tasks/evol_instruct/test_base.py
  tests/unit/steps/tasks/evol_instruct/test_generator.py
  tests/unit/steps/tasks/evol_quality/test_base.py
  tests/unit/steps/tasks/magpie/test_base.py
  tests/unit/steps/tasks/structured_outputs/test_outlines.py
  tests/unit/steps/tasks/test_base.py
  tests/unit/steps/tasks/test_decorator.py
  tests/unit/steps/tasks/test_improving_text_embeddings.py
  tests/unit/steps/tasks/test_instruction_backtranslation.py
  tests/unit/steps/tasks/test_structured_generation.py
  tests/unit/steps/tasks/test_text_classification.py
  tests/unit/steps/tasks/test_text_generation.py
  tests/unit/steps/tasks/test_ultrafeedback.py
Labels: enhancement

#1072 Fix StepOutput type
  src/distilabel/steps/typing.py
  tests/unit/steps/argilla/test_preference.py
Labels: fix
