Repository argilla-io/distilabel, pull requests merged in 2024-05, with the labels that each got.

#565 Set `streaming=False` and add `num_examples` to `LoadHubDataset`
  src/distilabel/steps/generators/huggingface.py
  tests/unit/steps/generators/test_huggingface.py
Labels: improvement

#566 Make `pipeline` argument of `Step` optional
  src/distilabel/steps/base.py
  tests/unit/pipeline/test_dag.py
  tests/unit/steps/argilla/test_base.py
  tests/unit/steps/tasks/evol_instruct/test_base.py
  tests/unit/steps/tasks/evol_instruct/test_generator.py
  tests/unit/steps/tasks/evol_quality/test_base.py
  tests/unit/steps/tasks/test_base.py
  tests/unit/steps/test_base.py
Labels: improvement

#594 Extend `LLM` kwargs to align with counterparts
  src/distilabel/llms/huggingface/inference_endpoints.py
  src/distilabel/llms/llamacpp.py
  src/distilabel/llms/vllm.py
  tests/unit/llms/test_llamacpp.py
Labels: fix, improvement

#600 Add `Genstruct` task
  src/distilabel/steps/tasks/__init__.py
  src/distilabel/steps/tasks/genstruct.py
  src/distilabel/steps/tasks/templates/genstruct.jinja2
  tests/unit/steps/tasks/test_genstruct.py
  tests/unit/test_imports.py
Labels: integrations

#603 Fix `num_examples` to be optional in `LoadHubDataset`
  src/distilabel/steps/generators/huggingface.py
Labels: fix

#610 Add `PrometheusEval` task
  src/distilabel/steps/tasks/__init__.py
  src/distilabel/steps/tasks/genstruct.py
  src/distilabel/steps/tasks/prometheus_eval.py
  src/distilabel/steps/tasks/templates/prometheus/absolute_with_reference.jinja2
  src/distilabel/steps/tasks/templates/prometheus/absolute_without_reference.jinja2
  src/distilabel/steps/tasks/templates/prometheus/relative_with_reference.jinja2
  src/distilabel/steps/tasks/templates/prometheus/relative_without_reference.jinja2
  src/distilabel/steps/tasks/ultrafeedback.py
  tests/unit/steps/tasks/test_prometheus_eval.py
  tests/unit/test_imports.py
Labels: integrations

#617 Update `ValueError` on missing inputs message
  docs/sections/learn/pipelines/index.md
  src/distilabel/llms/llamacpp.py
  src/distilabel/llms/vllm.py
  src/distilabel/pipeline/_dag.py
Labels: improvement

#598 Fix `pipeline.log` inconsistency & include LLM info in signature
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/utils/logging.py
Labels: fix

#621 Add custom `rubrics` attribute to `PrometheusEval`
  src/distilabel/steps/tasks/prometheus_eval.py
  tests/unit/steps/tasks/test_prometheus_eval.py
Labels: improvement

#620 Update `UltraFeedback` paper replication to use `routing_batch_function`
  docs/sections/papers/ultrafeedback.md
Labels: improvement

#586 Add `distilabel_meta` column to the datasets to include general data
  src/distilabel/distiset.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/steps/tasks/base.py
  tests/unit/steps/tasks/evol_instruct/test_base.py
  tests/unit/steps/tasks/evol_instruct/test_generator.py
  tests/unit/steps/tasks/evol_quality/test_base.py
  tests/unit/steps/tasks/test_base.py
  tests/unit/steps/tasks/test_text_generation.py
Labels: enhancement

#604 Add the option of passing the multiprocessing context via env var
  src/distilabel/pipeline/local.py
Labels: improvement

#628 Add `routing_batch_function` serialization
  src/distilabel/cli/pipeline/utils.py
  src/distilabel/pipeline/_dag.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/routing_batch_function.py
  src/distilabel/steps/base.py
  src/distilabel/utils/serialization.py
  tests/integration/test_routing_batch_function.py
  tests/unit/pipeline/test_base.py
  tests/unit/pipeline/test_dag.py
  tests/unit/pipeline/test_routing_batch_function.py
Labels: enhancement

#633 Excluding model path in serialization of llamacpp
  src/distilabel/llms/llamacpp.py
Labels: bug

#622 Fix problem with sorting method in `list_files_in_dir` function
  src/distilabel/utils/files.py
  tests/unit/utils/test_files.py
Labels: bug

#635 Add `dry_run` method to the pipelines to run with a single example.
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  tests/integration/test_dry_run.py
  tests/unit/pipeline/test_local.py
Labels: enhancement

#601 [FEATURE] Add structured outputs using `outlines`
  .github/workflows/test.yml
  pyproject.toml
  src/distilabel/llms/base.py
  src/distilabel/llms/huggingface/transformers.py
  src/distilabel/llms/llamacpp.py
  src/distilabel/llms/openai.py
  src/distilabel/llms/vllm.py
  src/distilabel/steps/tasks/structured_outputs/__init__.py
  src/distilabel/steps/tasks/structured_outputs/outlines.py
  tests/unit/helpers.py
  tests/unit/llms/huggingface/test_inference_endpoints.py
  tests/unit/llms/test_anthropic.py
  tests/unit/llms/test_anyscale.py
  tests/unit/llms/test_azure.py
  tests/unit/llms/test_cohere.py
  tests/unit/llms/test_groq.py
  tests/unit/llms/test_litellm.py
  tests/unit/llms/test_mistral.py
  tests/unit/llms/test_ollama.py
  tests/unit/llms/test_openai.py
  tests/unit/llms/test_together.py
  tests/unit/llms/test_vertexai.py
  tests/unit/steps/tasks/evol_instruct/test_base.py
  tests/unit/steps/tasks/evol_instruct/test_generator.py
  tests/unit/steps/tasks/evol_quality/test_base.py
  tests/unit/steps/tasks/structured_outputs/__init__.py
  tests/unit/steps/tasks/structured_outputs/test_outlines.py
  tests/unit/steps/tasks/test_base.py
Labels: enhancement, integrations

#630 Force pipeline stop after 2 SIGINT signals caught
  src/distilabel/pipeline/local.py
Labels: bug

#636 Update docs structured outputs
  docs/sections/components/llm/index.md
  examples/rpg_characters_llamacpp.py
  mkdocs.yml
Labels: documentation

#637 Update more docs
  docs/assets/images/sections/pipeline/pipeline-ctrlc.png
  docs/sections/components/advanced/caching.md
  docs/sections/components/advanced/distiset.md
  docs/sections/components/pipelines/index.md
  docs/sections/examples/index.md
  docs/sections/examples/papers/deita.md
  docs/sections/examples/papers/index.md
  docs/sections/examples/papers/instruction_backtranslation.md
  docs/sections/examples/papers/ultrafeedback.md
  mkdocs.yml
Labels: documentation

#638 Docs structured outputs advanced
  docs/sections/components/advanced/structured_generation.md
  docs/sections/components/llm/index.md
  mkdocs.yml
  src/distilabel/steps/tasks/structured_outputs/outlines.py
Labels: documentation

#639 Update FAQ layout
  docs/sections/faq.md
Labels: documentation

#641 refactor file name for explicitness
  docs/sections/components/advanced/structured_generation.md
  examples/structured_generation_with_outlines.py
Labels: documentation, refactor

#642 Fix file name to render docs
  docs/sections/examples/index.md
Labels: bug

#643 Collapse examples to simplify reading
  docs/sections/examples/index.md
Labels: documentation

#649 Fix routing batch function deadlocks and unordered batches
  .github/workflows/test.yml
  README.md
  pyproject.toml
  src/distilabel/distiset.py
  src/distilabel/pipeline/_dag.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/constants.py
  src/distilabel/pipeline/local.py
  src/distilabel/utils/serialization.py
  tests/integration/test_pipe_simple.py
  tests/integration/test_routing_batch_function.py
  tests/unit/pipeline/test_base.py
  tests/unit/pipeline/test_dag.py
Labels: fix

#658 Fix crash when using vLLM without structured generation
  src/distilabel/__init__.py
  src/distilabel/llms/vllm.py
Labels: fix

#655 Fix error on `Pipeline.dry_run` without `parameters`
  src/distilabel/__init__.py
  src/distilabel/pipeline/base.py
  tests/integration/test_dry_run.py
Labels: fix

#656 Add `prometheus.md`
  docs/sections/learn/advanced/argilla.md
  docs/sections/learn/advanced/structured_generation.md
  docs/sections/pipeline_samples/examples/index.md
  docs/sections/pipeline_samples/papers/prometheus.md
  mkdocs.yml
Labels: documentation

#672 Reduce time required to execute `_cache` method
  pyproject.toml
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/utils/serialization.py
  tests/unit/pipeline/test_base.py
Labels: enhancement

#675 Fix circular import due to DISTILABEL_METADATA_KEY
  src/distilabel/distiset.py
  src/distilabel/steps/constants.py
Labels: fix

#676 Deprecate conversation support in `TextGeneration` in favour of `ChatGeneration`
  src/distilabel/distiset.py
  src/distilabel/steps/tasks/text_generation.py
  tests/unit/steps/tasks/test_text_generation.py
Labels: deprecation

#673 Add functionality to load/save distisets to/from disk
  docs/sections/learn/advanced/distiset.md
  pyproject.toml
  src/distilabel/distiset.py
  tests/unit/test_distiset.py
Labels: enhancement

#679 Fix docs of saving/loading distiset from disk
  docs/sections/learn/advanced/distiset.md
Labels: documentation

#678 Pass data of batches using file system
  .github/workflows/test.yml
  docs/sections/learn/advanced/fs_to_pass_data.md
  mkdocs.yml
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/utils/logging.py
  tests/integration/conftest.py
  tests/integration/test_pipe_simple.py
  tests/integration/test_routing_batch_function.py
  tests/integration/test_using_fs_to_pass_data.py
  tests/unit/pipeline/test_base.py
  tests/unit/pipeline/test_local.py
Labels: enhancement, refactor

#615 Add `python==3.12`
  .github/workflows/test.yml
  .pre-commit-config.yaml
  Makefile
  pyproject.toml
  scripts/install_dependencies.sh
  src/distilabel/steps/argilla/base.py
  src/distilabel/steps/base.py
  src/distilabel/steps/decorator.py
  tests/unit/steps/argilla/test_base.py
  tests/unit/steps/tasks/test_base.py
Labels: enhancement

#674 Add `codspeed` benchmarks
  .github/workflows/codspeed.yml
  .github/workflows/test.yml
  pyproject.toml
  tests/integration/test_cache.py
Labels: enhancement, ci
