Repository argilla-io/distilabel, pull requests merged in 2024-03, with the labels that each got.

#367 Add `input_mappings` and `output_mappings` attributes
  .github/workflows/test.yml
  Makefile
  src/distilabel/pipeline/_dag.py
  src/distilabel/pipeline/local.py
  src/distilabel/pipeline/step/base.py
  src/distilabel/utils/__init__.py
  src/distilabel/utils/serialization.py
  tests/pipeline/llm/test_serialization.py
  tests/pipeline/step/test_base.py
  tests/pipeline/test_dag.py
Labels: enhancement

#371 Move batching from `Task` to `LLM`, fix `vLLM.generate` and add `DISTILABEL_LOG_LEVEL`
  src/distilabel/pipeline/llm/base.py
  src/distilabel/pipeline/llm/llamacpp.py
  src/distilabel/pipeline/llm/openai.py
  src/distilabel/pipeline/llm/transformers.py
  src/distilabel/pipeline/llm/vllm.py
  src/distilabel/pipeline/logging.py
  src/distilabel/pipeline/step/task/base.py
Labels: fix, improvement

#381 Add `AsyncOpenAI` and update `OpenAILLM` accordingly
  pyproject.toml
  src/distilabel/llm/__init__.py
  src/distilabel/llm/base.py
  src/distilabel/llm/huggingface/__init__.py
  src/distilabel/llm/huggingface/transformers.py
  src/distilabel/llm/llamacpp.py
  src/distilabel/llm/openai.py
  src/distilabel/llm/vllm.py
  src/distilabel/pipeline/llm/base.py
  src/distilabel/pipeline/llm/openai.py
  src/distilabel/pipeline/step/base.py
  src/distilabel/pipeline/step/task/base.py
  tests/integration/test_pipe_llms.py
  tests/unit/llm/__init__.py
  tests/unit/llm/openai.py
  tests/unit/pipeline/llm/test_serialization.py
  tests/unit/pipeline/test_base.py
Labels: improvement

#382 Update serde
  pyproject.toml
  src/distilabel/llm/base.py
  src/distilabel/pipeline/_dag.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/serialization.py
  src/distilabel/pipeline/step/base.py
  src/distilabel/pipeline/step/generators/huggingface.py
  src/distilabel/pipeline/step/globals/huggingface.py
  src/distilabel/utils/serialization.py
  tests/unit/pipeline/step/test_base.py
  tests/unit/pipeline/test_base.py
  tests/unit/pipeline/test_dag.py
Labels: enhancement

#384 Move `steps` out of `pipeline`
  src/distilabel/llm/base.py
  src/distilabel/llm/huggingface/transformers.py
  src/distilabel/llm/llamacpp.py
  src/distilabel/llm/mistral.py
  src/distilabel/llm/openai.py
  src/distilabel/llm/vllm.py
  src/distilabel/pipeline/_dag.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/pipeline/utils.py
  src/distilabel/steps/__init__.py
  src/distilabel/steps/base.py
  src/distilabel/steps/combine.py
  src/distilabel/steps/generators/__init__.py
  src/distilabel/steps/generators/huggingface.py
  src/distilabel/steps/globals/__init__.py
  src/distilabel/steps/globals/huggingface.py
  src/distilabel/steps/task/__init__.py
  src/distilabel/steps/task/base.py
  src/distilabel/steps/task/generation.py
  src/distilabel/steps/task/typing.py
  src/distilabel/steps/typing.py
  tests/integration/test_pipe_llms.py
  tests/integration/test_pipe_simple.py
  tests/unit/pipeline/test_base.py
  tests/unit/pipeline/test_dag.py
  tests/unit/pipeline/test_local.py
  tests/unit/pipeline/utils.py
  tests/unit/steps/__init__.py
  tests/unit/steps/test_base.py
Labels: refactor

#399 Add `input` propagation through `Task.process`
  src/distilabel/steps/task/base.py
Labels: fix

#400 Improve `Pipeline` error handling
  src/distilabel/pipeline/_dag.py
  src/distilabel/pipeline/local.py
  tests/unit/pipeline/test_local.py
Labels: enhancement

#402 Improve `GlobalStep` error handling
  src/distilabel/pipeline/_dag.py
  src/distilabel/pipeline/local.py
  tests/unit/pipeline/test_dag.py
Labels: enhancement

#407 Add `EvolInstruct` and `EvolInstructGenerator` tasks
  src/distilabel/llm/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/steps/base.py
  src/distilabel/steps/generators/huggingface.py
  src/distilabel/steps/globals/huggingface.py
  src/distilabel/steps/task/base.py
  src/distilabel/steps/task/evol_instruct/__init__.py
  src/distilabel/steps/task/evol_instruct/base.py
  src/distilabel/steps/task/evol_instruct/english_nouns.txt
  src/distilabel/steps/task/evol_instruct/generator.py
  src/distilabel/steps/task/evol_instruct/utils.py
  src/distilabel/steps/task/text_generation.py
  src/distilabel/utils/serialization.py
  tests/unit/steps/task/evol_instruct/__init__.py
  tests/unit/steps/task/evol_instruct/test_base.py
  tests/unit/steps/task/evol_instruct/test_generator.py
Labels: enhancement, task

#428 Wrap optional `LLM` dependencies under `load`
  src/distilabel/llm/base.py
  src/distilabel/llm/huggingface/transformers.py
  src/distilabel/llm/llamacpp.py
  src/distilabel/llm/mistral.py
  src/distilabel/llm/openai.py
  src/distilabel/llm/vllm.py
Labels: fix

#421 Add `ComplexityScorer` task
  src/distilabel/steps/task/base.py
  src/distilabel/steps/task/complexity_scorer.py
  src/distilabel/steps/task/evol_instruct/generator.py
  src/distilabel/steps/task/text_generation.py
  tests/unit/steps/task/test_base.py
  tests/unit/steps/task/test_complexity_score.py
Labels: enhancement

#370 Implement caching mechanism for the pipelines
  src/distilabel/pipeline/_dag.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/steps/base.py
  src/distilabel/steps/generators/huggingface.py
  tests/integration/test_pipe_simple.py
  tests/unit/pipeline/test_base.py
  tests/unit/pipeline/test_local.py
Labels: enhancement

#406 Add method to Pipeline to handle keyboard interruptions via ctrl+c
  src/distilabel/pipeline/local.py
Labels: enhancement

#427 Add `GenerateEmbeddings` task
  src/distilabel/pipeline/local.py
  src/distilabel/steps/base.py
  src/distilabel/steps/generators/huggingface.py
  src/distilabel/steps/task/base.py
  src/distilabel/steps/task/generate_embeddings.py
  src/distilabel/utils/chat.py
  tests/unit/steps/task/test_generate_embeddings.py
  tests/unit/steps/task/test_text_generation.py
  tests/unit/utils/test_chat.py
Labels: enhancement

#432 Add `api_key` within `LLM.load` and add `llm_kwargs` as `RuntimeParameter`
  src/distilabel/llm/base.py
  src/distilabel/llm/mistral.py
  src/distilabel/llm/openai.py
  src/distilabel/pipeline/local.py
  src/distilabel/steps/task/base.py
  tests/unit/llm/test_llamacpp.py
  tests/unit/llm/test_transformers.py
  tests/unit/steps/task/evol_instruct/test_base.py
  tests/unit/steps/task/evol_instruct/test_generator.py
  tests/unit/steps/task/test_base.py
Labels: improvement

#435 Add `GeneratorStep.process` validation in `DAG` and smaller fixes
  src/distilabel/integrations/argilla/base.py
  src/distilabel/integrations/argilla/prompt_completion.py
  src/distilabel/pipeline/_dag.py
  src/distilabel/pipeline/local.py
  src/distilabel/steps/base.py
  src/distilabel/steps/combine.py
  src/distilabel/steps/generators/huggingface.py
  src/distilabel/steps/globals/huggingface.py
  src/distilabel/steps/task/base.py
  src/distilabel/steps/task/evol_instruct/base.py
  src/distilabel/steps/task/evol_instruct/generator.py
  src/distilabel/steps/task/generate_embeddings.py
  tests/unit/integrations/argilla/test_base.py
  tests/unit/pipeline/test_dag.py
  tests/unit/pipeline/utils.py
Labels: fix

#415 Add `EvolComplexity` task
  src/distilabel/steps/task/base.py
  src/distilabel/steps/task/evol_instruct/base.py
  src/distilabel/steps/task/evol_instruct/evol_complexity/__init__.py
  src/distilabel/steps/task/evol_instruct/evol_complexity/base.py
  src/distilabel/steps/task/evol_instruct/evol_complexity/generator.py
  src/distilabel/steps/task/evol_instruct/evol_complexity/utils.py
  src/distilabel/steps/task/evol_instruct/generator.py
  src/distilabel/steps/task/evol_instruct/utils.py
  tests/unit/steps/task/evol_instruct/conftest.py
  tests/unit/steps/task/evol_instruct/evol_complexity.py/test_base.py
  tests/unit/steps/task/evol_instruct/evol_complexity.py/test_generator.py
  tests/unit/steps/task/evol_instruct/test_base.py
  tests/unit/steps/task/evol_instruct/test_generator.py
Labels: integrations

#425 Add `QualityScorer` Task
  src/distilabel/steps/task/quality_scorer.py
  tests/unit/steps/task/test_quality_scorer.py
Labels: integrations

#440 Fix some issues impacting `EvolInstruct` and `EvolComplexity`
  src/distilabel/steps/task/evol_instruct/base.py
  src/distilabel/steps/task/evol_instruct/evol_complexity/base.py
  src/distilabel/steps/task/evol_instruct/evol_complexity/generator.py
  src/distilabel/steps/task/evol_instruct/evol_complexity/utils.py
  src/distilabel/steps/task/evol_instruct/generator.py
  src/distilabel/steps/task/evol_instruct/utils.py
  tests/unit/steps/task/conftest.py
  tests/unit/steps/task/evol_instruct/conftest.py
  tests/unit/steps/task/evol_instruct/evol_complexity.py/__init__.py
  tests/unit/steps/task/evol_instruct/evol_complexity.py/test_base.py
  tests/unit/steps/task/evol_instruct/evol_complexity.py/test_generator.py
  tests/unit/steps/task/evol_instruct/test_base.py
  tests/unit/steps/task/evol_instruct/test_generator.py
Labels: fix

#417 Return `distiset` from `Pipeline.run`
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/utils/distiset.py
  tests/integration/test_pipe_simple.py
  tests/unit/pipeline/test_base.py
  tests/unit/pipeline/test_local.py
  tests/unit/pipeline/utils.py
  tests/unit/utils/test_data.py
Labels: enhancement

#452 Fix `Distiset` after `PushToHub` and smaller fixes
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/steps/globals/huggingface.py
  src/distilabel/utils/distiset.py
Labels: fix

#453 Fix `Step.process_applying_mappings`
  src/distilabel/steps/base.py
  tests/unit/steps/test_base.py
Labels: fix

#454 Add general function to obtain schema for parquet writer
  src/distilabel/pipeline/base.py
  tests/unit/pipeline/test_base.py
  tests/unit/pipeline/test_local.py
Labels: fix

#449 Add `TogetherLLM`
  src/distilabel/llm/together.py
  tests/unit/llm/test_together.py
Labels: integrations

#455 Fix `LLM` subclasses based on `OpenAILLM`
  src/distilabel/llm/anyscale.py
  src/distilabel/llm/base.py
  src/distilabel/llm/openai.py
  src/distilabel/llm/together.py
  tests/unit/llm/test_anyscale.py
  tests/unit/llm/test_openai.py
  tests/unit/llm/test_together.py
Labels: fix

#457 Improve batching and caching
  src/distilabel/llm/mixins.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/steps/base.py
  src/distilabel/steps/decorator.py
  src/distilabel/steps/generators/huggingface.py
  src/distilabel/utils/logging.py
  tests/integration/test_pipe_simple.py
  tests/unit/llm/test_mixins.py
  tests/unit/pipeline/test_base.py
  tests/unit/steps/test_decorator.py
Labels: enhancement

#445 Add `VertexAILLM`
  src/distilabel/llm/vertexai.py
  tests/unit/llm/test_vertexai.py
Labels: integrations

#463 Add `use_cache` to `BasePipeline`
  src/distilabel/pipeline/base.py
  tests/unit/pipeline/test_base.py
Labels: enhancement

#444 Add `AnthropicLLM`
  .github/workflows/test.yml
  pyproject.toml
  src/distilabel/llm/anthropic.py
  tests/unit/llm/test_anthropic.py
Labels: integrations

#467 Add `multiprocess` dependency
  pyproject.toml
  src/distilabel/pipeline/local.py
Labels: enhancement

#464 Add `UltraFeedback`
  src/distilabel/llm/huggingface/inference_endpoints.py
  src/distilabel/pipeline/local.py
  src/distilabel/steps/task/complexity_scorer.py
  src/distilabel/steps/task/quality_scorer.py
  src/distilabel/steps/task/templates/ultrafeedback/helpfulness.jinja2
  src/distilabel/steps/task/templates/ultrafeedback/honesty.jinja2
  src/distilabel/steps/task/templates/ultrafeedback/instruction-following.jinja2
  src/distilabel/steps/task/templates/ultrafeedback/overall-rating.jinja2
  src/distilabel/steps/task/templates/ultrafeedback/truthfulness.jinja2
  src/distilabel/steps/task/ultrafeedback.py
  tests/unit/steps/task/evol_quality/__init__.py
  tests/unit/steps/task/evol_quality/test_base.py
  tests/unit/steps/task/test_complexity_scorer.py
  tests/unit/steps/task/test_ultrafeedback.py
Labels: fix, integrations

#405 Add `OllamaLLM`
  pyproject.toml
  src/distilabel/llm/ollama.py
  tests/unit/llm/test_ollama.py
Labels: integrations

#466 Add `RuntimeParametersMixin` and `LLM` runtime parameters
  src/distilabel/llm/anthropic.py
  src/distilabel/llm/anyscale.py
  src/distilabel/llm/base.py
  src/distilabel/llm/huggingface/inference_endpoints.py
  src/distilabel/llm/mistral.py
  src/distilabel/llm/ollama.py
  src/distilabel/llm/openai.py
  src/distilabel/llm/together.py
  src/distilabel/llm/vertexai.py
  src/distilabel/mixins/__init__.py
  src/distilabel/mixins/runtime_parameters.py
  src/distilabel/pipeline/_dag.py
  src/distilabel/pipeline/base.py
  src/distilabel/steps/base.py
  src/distilabel/steps/decorator.py
  src/distilabel/steps/generators/huggingface.py
  src/distilabel/steps/globals/huggingface.py
  src/distilabel/steps/task/base.py
  src/distilabel/steps/task/evol_instruct/base.py
  src/distilabel/steps/task/evol_instruct/generator.py
  src/distilabel/steps/task/evol_quality/base.py
  src/distilabel/utils/docstring.py
  src/distilabel/utils/typing_.py
  tests/integration/test_pipe_llms.py
  tests/integration/test_pipe_simple.py
  tests/unit/llm/huggingface/test_inference_endpoints.py
  tests/unit/llm/test_anthropic.py
  tests/unit/llm/test_anyscale.py
  tests/unit/llm/test_mistral.py
  tests/unit/llm/test_ollama.py
  tests/unit/llm/test_openai.py
  tests/unit/llm/test_together.py
  tests/unit/llm/test_vertexai.py
  tests/unit/mixins/__init__.py
  tests/unit/mixins/test_runtime_parameters.py
  tests/unit/pipeline/test_dag.py
  tests/unit/steps/task/evol_instruct/evol_complexity.py/test_base.py
  tests/unit/steps/task/evol_instruct/evol_complexity.py/test_generator.py
  tests/unit/steps/task/evol_instruct/test_base.py
  tests/unit/steps/task/evol_instruct/test_generator.py
  tests/unit/steps/task/evol_quality/test_base.py
  tests/unit/steps/task/test_base.py
  tests/unit/steps/task/test_generate_embeddings.py
  tests/unit/steps/test_base.py
  tests/unit/steps/test_decorator.py
  tests/unit/utils/test_docstring.py
  tests/unit/utils/test_typing.py
Labels: enhancement

#441 Add `LiteLLM`
  .github/workflows/test.yml
  pyproject.toml
  src/distilabel/llm/litellm.py
  src/distilabel/llm/ollama.py
  tests/unit/llm/test_litellm.py
  tests/unit/llm/test_ollama.py
Labels: integrations

#474 Add `overload` to `step` decorator
  src/distilabel/steps/decorator.py
Labels: enhancement

#482 Move Enum to Dict[str, str] to avoid serialization errors during caching
  src/distilabel/pipeline/local.py
  src/distilabel/steps/task/evol_instruct/base.py
  src/distilabel/steps/task/evol_instruct/evol_complexity/base.py
  src/distilabel/steps/task/evol_instruct/evol_complexity/generator.py
  src/distilabel/steps/task/evol_instruct/evol_complexity/utils.py
  src/distilabel/steps/task/evol_instruct/generator.py
  src/distilabel/steps/task/evol_instruct/utils.py
  tests/unit/steps/task/evol_instruct/evol_complexity.py/test_base.py
  tests/unit/steps/task/evol_instruct/evol_complexity.py/test_generator.py
  tests/unit/steps/task/evol_instruct/test_base.py
  tests/unit/steps/task/evol_instruct/test_generator.py
Labels: fix, refactor

#479 Include a dataset card and the `pipeline.yaml` on `Distiset.push_to_hub`
  src/distilabel/pipeline/local.py
  src/distilabel/utils/card/__init__.py
  src/distilabel/utils/card/dataset_card.py
  src/distilabel/utils/card/distilabel_template.md
  src/distilabel/utils/distiset.py
Labels: enhancement

#450 Add `PairRM` task for ranking responses
  .github/workflows/test.yml
  src/distilabel/steps/task/pair_rm.py
  tests/unit/steps/task/test_pair_rm.py
Labels: enhancement

#483 Update `_WriteBuffer` to write several parquet files
  src/distilabel/pipeline/base.py
  src/distilabel/utils/distiset.py
  src/distilabel/utils/files.py
  src/distilabel/utils/logging.py
  tests/integration/test_pipe_simple.py
  tests/unit/pipeline/test_base.py
  tests/unit/pipeline/utils.py
Labels: enhancement, fix

#472 Extend `Argilla` integration `TextGeneration`, `Preference`, and more
  src/distilabel/integrations/argilla/__init__.py
  src/distilabel/integrations/argilla/base.py
  src/distilabel/integrations/argilla/preference.py
  src/distilabel/integrations/argilla/prompt_completion.py
  src/distilabel/integrations/argilla/text_generation.py
  src/distilabel/llm/huggingface/inference_endpoints.py
  src/distilabel/llm/huggingface/transformers.py
  src/distilabel/llm/llamacpp.py
  src/distilabel/llm/mistral.py
  src/distilabel/llm/mixins.py
  src/distilabel/llm/openai.py
  src/distilabel/llm/vllm.py
  src/distilabel/pipeline/local.py
  src/distilabel/steps/combine.py
  src/distilabel/steps/decorator.py
  src/distilabel/steps/keep.py
  src/distilabel/steps/task/base.py
  src/distilabel/steps/task/evol_quality/base.py
  tests/unit/integrations/argilla/test_base.py
  tests/unit/integrations/argilla/test_preference.py
  tests/unit/integrations/argilla/test_text_generation.py
  tests/unit/pipeline/test_base.py
  tests/unit/steps/task/test_quality_scorer.py
  tests/unit/steps/test_combine.py
  tests/unit/steps/test_keep.py
Labels: argilla

#481 Add `DeitaFiltering` step
  src/distilabel/llm/huggingface/transformers.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/steps/conversation.py
  src/distilabel/steps/deita.py
  src/distilabel/steps/expand.py
  src/distilabel/steps/globals/huggingface.py
  src/distilabel/steps/task/complexity_scorer.py
  src/distilabel/steps/task/evol_instruct/base.py
  src/distilabel/steps/task/evol_quality/base.py
  src/distilabel/steps/task/evol_quality/utils.py
  src/distilabel/steps/task/generate_embeddings.py
  src/distilabel/steps/task/quality_scorer.py
  tests/unit/pipeline/test_base.py
  tests/unit/steps/task/conftest.py
  tests/unit/steps/task/evol_instruct/test_base.py
  tests/unit/steps/task/evol_quality/test_base.py
  tests/unit/steps/task/test_pair_rm.py
  tests/unit/steps/test_conversation.py
  tests/unit/steps/test_deita.py
  tests/unit/steps/test_expand.py
Labels: enhancement

#486 Add `InstructionBacktranslation`
  src/distilabel/steps/task/instruction_backtranslation.py
  src/distilabel/steps/task/templates/instruction-backtranslation.jinja2
  src/distilabel/steps/task/templates/ultrafeedback/helpfulness.jinja2
  tests/unit/steps/__init__.py
  tests/unit/steps/task/test_instruction_backtranslation.py
Labels: fix, integrations

#485 Fix huggingface_hub TextGenerationError import
  pyproject.toml
  src/distilabel/llm/huggingface/inference_endpoints.py
  src/distilabel/utils/imports.py
Labels: fix

#461 Improve azure openai support
  README.md
  src/distilabel/llm/openai.py
Labels: improvement

#489 Use `QueueHandler` for `Pipeline` logging
  src/distilabel/llm/anthropic.py
  src/distilabel/llm/base.py
  src/distilabel/llm/huggingface/inference_endpoints.py
  src/distilabel/llm/huggingface/transformers.py
  src/distilabel/llm/litellm.py
  src/distilabel/llm/llamacpp.py
  src/distilabel/llm/mistral.py
  src/distilabel/llm/ollama.py
  src/distilabel/llm/openai.py
  src/distilabel/llm/vertexai.py
  src/distilabel/llm/vllm.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/steps/base.py
  src/distilabel/steps/generators/huggingface.py
  src/distilabel/steps/task/base.py
  src/distilabel/steps/task/generate_embeddings.py
  src/distilabel/utils/distiset.py
  src/distilabel/utils/logging.py
  tests/unit/llm/test_mixins.py
  tests/unit/steps/task/evol_instruct/test_base.py
  tests/unit/steps/task/evol_instruct/test_generator.py
  tests/unit/steps/task/evol_quality/test_base.py
Labels: enhancement, fix
