Repository argilla-io/distilabel, pull requests merged in 2024-04, with the labels that each got.

#491 Improve `_stop` and `logging`
  src/distilabel/pipeline/local.py
  src/distilabel/utils/logging.py
Labels: enhancement, fix

#492 Fix creating empty `Dataset` in `create_distiset` function
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/steps/base.py
  src/distilabel/utils/distiset.py
  src/distilabel/utils/logging.py
Labels: fix

#493 Add imports from `__init__` modules
  src/distilabel/distiset.py
  src/distilabel/llm/__init__.py
  src/distilabel/llm/anthropic.py
  src/distilabel/llm/anyscale.py
  src/distilabel/llm/base.py
  src/distilabel/llm/litellm.py
  src/distilabel/llm/llamacpp.py
  src/distilabel/llm/mistral.py
  src/distilabel/llm/ollama.py
  src/distilabel/llm/openai.py
  src/distilabel/llm/together.py
  src/distilabel/llm/vertexai.py
  src/distilabel/llm/vllm.py
  src/distilabel/pipeline/__init__.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/steps/__init__.py
  src/distilabel/steps/argilla/__init__.py
  src/distilabel/steps/argilla/base.py
  src/distilabel/steps/argilla/preference.py
  src/distilabel/steps/argilla/text_generation.py
  src/distilabel/steps/base.py
  src/distilabel/tasks/__init__.py
  src/distilabel/utils/logging.py
  tests/integration/test_pipe_simple.py
  tests/unit/integrations/__init__.py
  tests/unit/integrations/argilla/__init__.py
  tests/unit/llm/test_anthropic.py
  tests/unit/llm/test_anyscale.py
  tests/unit/llm/test_mistral.py
  tests/unit/llm/test_openai.py
  tests/unit/llm/test_together.py
  tests/unit/pipeline/test_base.py
  tests/unit/steps/argilla/__init__.py
  tests/unit/steps/argilla/test_base.py
  tests/unit/steps/argilla/test_preference.py
  tests/unit/steps/argilla/test_text_generation.py
  tests/unit/test_distiset.py
  tests/unit/test_imports.py
Labels: enhancement

#495 `batch_size` and `input_batch_size` runtime parameters
  src/distilabel/steps/base.py
  tests/unit/pipeline/test_base.py
  tests/unit/steps/argilla/test_base.py
  tests/unit/steps/argilla/test_preference.py
  tests/unit/steps/argilla/test_text_generation.py
  tests/unit/steps/task/evol_instruct/test_base.py
  tests/unit/steps/task/evol_instruct/test_generator.py
  tests/unit/steps/task/evol_quality/test_base.py
  tests/unit/steps/task/test_base.py
  tests/unit/steps/test_base.py
  tests/unit/steps/test_decorator.py
Labels: enhancement

#496 Update serialization method of _BatchManager to write each step on its own file
  src/distilabel/pipeline/base.py
  src/distilabel/utils/serialization.py
  tests/unit/pipeline/test_base.py
Labels: enhancement

#501 Fix `asyncio` in `AsyncLLM` to use the running event loop if any
  pyproject.toml
  src/distilabel/llm/base.py
  src/distilabel/utils/notebook.py
Labels: fix

#498 Added authentication header to allow private/gated dataset use
  src/distilabel/cli/pipeline/utils.py
  src/distilabel/steps/argilla/base.py
  src/distilabel/steps/generators/huggingface.py
Labels: fix

#505 Add `AzureOpenAILLM`
  README.md
  docs/api/llms/azure.md
  docs/index.md
  pyproject.toml
  src/distilabel/llms/__init__.py
  src/distilabel/llms/azure.py
  tests/unit/llms/test_azure.py
  tests/unit/test_imports.py
Labels: enhancement

#503 Docs steps
  docs/api/steps/decorator.md
  docs/sections/learn/index.md
  docs/sections/learn/steps/general_steps.md
  docs/sections/learn/steps/generator_steps.md
  docs/sections/learn/steps/global_steps.md
  docs/sections/learn/steps/index.md
  docs/sections/learn/steps/steps.md
  docs/sections/learn/tasks/feedback_tasks.md
  docs/sections/learn/tasks/index.md
  docs/sections/learn/tasks/special_tasks.md
  docs/sections/learn/tasks/text_generation.md
  mkdocs.yml
Labels: documentation

#504 Deita tutorial for docs
  docs/assets/tutorials-assets/deita/datasets.png
  docs/assets/tutorials-assets/deita/diversity.png
  docs/assets/tutorials-assets/deita/overview.png
  docs/assets/tutorials-assets/deita/results.png
  docs/sections/papers/deita.md
  mkdocs.yml
Labels: tutorial

#510 Fix generator yielding batches all at once if `batch_size` == `input_batch_size`
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/steps/generators/data.py
  tests/integration/test_pipe_simple.py
  tests/unit/pipeline/test_base.py
Labels: fix

#506 Docs tasks
  docs/sections/learn/steps/index.md
  docs/sections/learn/tasks/feedback_tasks.md
  docs/sections/learn/tasks/index.md
  docs/sections/learn/tasks/text_generation.md
  src/distilabel/llms/vllm.py
Labels: documentation

#511 Run output queue loop in thread and improve stop
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  tests/unit/pipeline/test_base.py
  tests/unit/pipeline/test_local.py
Labels: enhancement, fix

#509 Add `docs/sections/learn/argilla.md`
  docs/assets/images/sections/learn/steps/argilla/preference.png
  docs/assets/images/sections/learn/steps/argilla/text_generation.png
  docs/sections/learn/steps/argilla.md
  docs/sections/learn/steps/general_steps.md
  docs/sections/learn/tasks/index.md
  docs/sections/learn/tasks/text_generation.md
  mkdocs.yml
Labels: documentation, argilla

#514 Add `docs/sections/learn/llms/index.md`
  docs/sections/learn/llms/index.md
Labels: documentation

#512 Docs pipeline
  docs/sections/learn/cli.md
  docs/sections/learn/pipelines/index.md
  mkdocs.yml
Labels: documentation

#508 Add `CohereLLM`
  .github/workflows/test.yml
  docs/sections/learn/llms/index.md
  docs/sections/learn/tasks/index.md
  mkdocs.yml
  pyproject.toml
  src/distilabel/llms/__init__.py
  src/distilabel/llms/cohere.py
  tests/unit/llms/test_cohere.py
Labels: enhancement

#516 Fix `docs/sections/papers/*.md` and add example in `docs/index.md`
  docs/index.md
  docs/sections/papers/deita.md
  docs/sections/papers/instruction_backtranslation.md
  docs/sections/papers/ultrafeedback.md
  mkdocs.yml
Labels: documentation

#521 Fix CTRL + C when still loading steps
  src/distilabel/pipeline/local.py
  tests/unit/steps/argilla/test_base.py
  tests/unit/steps/argilla/test_preference.py
  tests/unit/steps/argilla/test_text_generation.py
Labels: fix

#528 Empty input queues when `CTRL + C`
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  tests/unit/pipeline/test_base.py
Labels: enhancement

#529 Add `filelock` and `flash-attn` to `vllm` extra
  pyproject.toml
Labels: dependencies, fix

#530 Fix error in README.md when pushing the custom dataset card
  src/distilabel/distiset.py
Labels: fix

#531 Fix pipeline stuck when empty batches
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  tests/unit/pipeline/test_base.py
Labels: fix

#532 Show information about subprocess exception
  pyproject.toml
  src/distilabel/__init__.py
  src/distilabel/pipeline/local.py
Labels: enhancement

#533 Update `TextGeneration.format_input` method to allow OpenAI format
  src/distilabel/steps/tasks/text_generation.py
  tests/unit/steps/tasks/test_text_generation.py
  tests/unit/utils/test_chat.py
Labels: enhancement

#534 Improve create_distiset
  docs/sections/learn/caching.md
  src/distilabel/distiset.py
Labels: enhancement

#535 Fixes regarding `RuntimeParameter`s and `pydantic` model attributes
  src/distilabel/distiset.py
  src/distilabel/llms/base.py
  src/distilabel/mixins/runtime_parameters.py
  src/distilabel/pipeline/base.py
  src/distilabel/steps/argilla/base.py
  src/distilabel/steps/base.py
Labels: fix

#537 Fix parsing `LLM` generation kwargs
  docs/sections/learn/llms/index.md
  src/distilabel/llms/anthropic.py
  src/distilabel/llms/cohere.py
  src/distilabel/llms/huggingface/inference_endpoints.py
  src/distilabel/llms/huggingface/transformers.py
  src/distilabel/llms/litellm.py
  src/distilabel/llms/llamacpp.py
  src/distilabel/llms/mistral.py
  src/distilabel/llms/ollama.py
  src/distilabel/llms/openai.py
  src/distilabel/llms/vertexai.py
  src/distilabel/llms/vllm.py
  src/distilabel/steps/tasks/typing.py
  tests/unit/llms/test_ollama.py
Labels: fix

#540 Set `config="default"` in `Distiset` when only one leaf `Step`
  .pre-commit-config.yaml
  docs/sections/learn/caching.md
  docs/sections/learn/cli.md
  docs/sections/learn/distiset.md
  docs/sections/learn/steps/generator_steps.md
  docs/sections/learn/steps/global_steps.md
  docs/sections/learn/steps/index.md
  docs/sections/learn/tasks/feedback_tasks.md
  docs/sections/learn/tasks/text_generation.md
  docs/sections/papers/deita.md
  docs/snippets/technical-reference/pipeline/pipeline_dataset_checkpoint_4.py
  docs/snippets/technical-reference/tasks/complexity_scorer_example.py
  docs/snippets/technical-reference/tasks/evol_quality_example.py
  docs/snippets/technical-reference/tasks/quality_scorer_example.py
  docs/tutorials/create-evol-instruct-dataset.ipynb
  src/distilabel/distiset.py
  src/distilabel/steps/tasks/pair_rm.py
  src/distilabel/utils/card/distilabel_template.md
  tests/integration/test_pipe_simple.py
  tests/unit/pipeline/test_base.py
  tests/unit/test_distiset.py
Labels: documentation, fix

#542 Remove `flash-attn` from `vllm` extra
  pyproject.toml
Labels: fix

#543 Fix not all exceptions being able to be pickled
  src/distilabel/__init__.py
  src/distilabel/pipeline/local.py
Labels: fix

#544 Update CLI example
  README.md
  docs/assets/images/sections/cli/cli_pipe.png
  docs/assets/images/sections/cli/cli_pipe_1.png
  docs/assets/images/sections/cli/cli_pipe_2.png
  docs/index.md
  docs/sections/learn/cli.md
Labels: documentation

#545 Check that `Step.name` doesn't contain dots or spaces
  src/distilabel/steps/base.py
  tests/unit/steps/test_base.py
Labels: enhancement

#490 Allow nested connect calls and overload rshift method to connect steps
  docs/sections/learn/pipelines/index.md
  mkdocs.yml
  src/distilabel/steps/base.py
  tests/unit/pipeline/test_base.py
Labels: enhancement

#552 Fix `model_validator` in `InferenceEndpoints` due to `Pipeline` pickling
  src/distilabel/__init__.py
  src/distilabel/llms/huggingface/inference_endpoints.py
Labels: fix

#557 Fix `llm_blender` installation
  .github/workflows/test.yml
Labels: dependencies, fix

#555 Warn user about unknown runtime parameters
  src/distilabel/mixins/runtime_parameters.py
  tests/unit/pipeline/test_base.py
Labels: improvement

#560 Add missing `model_name`, update docstrings, and add `*.jinja2` templates to `Task` subclasses
  src/distilabel/steps/tasks/complexity_scorer.py
  src/distilabel/steps/tasks/generate_embeddings.py
  src/distilabel/steps/tasks/instruction_backtranslation.py
  src/distilabel/steps/tasks/pair_rm.py
  src/distilabel/steps/tasks/quality_scorer.py
  src/distilabel/steps/tasks/self_instruct.py
  src/distilabel/steps/tasks/templates/complexity-scorer.jinja2
  src/distilabel/steps/tasks/templates/quality-scorer.jinja2
  src/distilabel/steps/tasks/ultrafeedback.py
  tests/unit/steps/tasks/test_pair_rm.py
Labels: fix

#558 Split `ChatGeneration` from `TextGeneration`
  docs/api/steps/tasks/preference_tasks.md
  docs/api/steps/tasks/text_generation.md
  docs/sections/learn/tasks/text_generation.md
  src/distilabel/steps/tasks/__init__.py
  src/distilabel/steps/tasks/text_generation.py
  tests/unit/steps/tasks/test_text_generation.py
Labels: improvement, deprecation

#564 Fix `RuntimeParamater` validation when provided as `_Step` attr
  .github/workflows/test.yml
  src/distilabel/__init__.py
  src/distilabel/mixins/runtime_parameters.py
  src/distilabel/pipeline/_dag.py
  tests/unit/pipeline/test_dag.py
  tests/unit/steps/tasks/test_base.py
Labels: fix

#571 Add `seed` with `random.randint` to ensure cache is not used
  src/distilabel/llms/huggingface/inference_endpoints.py
Labels: fix

#575 Infer step name
  src/distilabel/pipeline/base.py
  src/distilabel/steps/base.py
  tests/unit/pipeline/test_base.py
  tests/unit/steps/test_base.py
Labels: enhancement

#578 Change the context of subprocesses depending on the platform
  src/distilabel/pipeline/local.py
Labels: bug

#585 Add `stop` and `stop_sequences` in `LLM.generate` subclasses
  src/distilabel/__init__.py
  src/distilabel/llms/huggingface/inference_endpoints.py
  src/distilabel/llms/openai.py
  src/distilabel/llms/vllm.py
Labels: fix, improvement

#568 Dump logs within a file in .cache/distilabel/pipelines dir
  src/distilabel/distiset.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/utils/logging.py
Labels: enhancement

#590 Fix empty batches causing missaligment when branching
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  tests/integration/test_branching_missaligmnent.py
  tests/unit/pipeline/test_base.py
Labels: fix

#583 Add `GroqLLM`
  .github/workflows/test.yml
  README.md
  docs/api/llms/groq.md
  docs/index.md
  docs/sections/learn/llms/index.md
  mkdocs.yml
  pyproject.toml
  src/distilabel/llms/__init__.py
  src/distilabel/llms/cohere.py
  src/distilabel/llms/groq.py
  tests/unit/llms/test_groq.py
Labels: integrations

#584 Add `Format{Chat,Text}Generation{DPO,SFT}`
  src/distilabel/steps/formatting/__init__.py
  src/distilabel/steps/formatting/dpo.py
  src/distilabel/steps/formatting/sft.py
  tests/unit/steps/formatting/__init__.py
  tests/unit/steps/formatting/test_dpo.py
  tests/unit/steps/formatting/test_sft.py
Labels: enhancement

#597 Fix `title` in `RatingQuestion` of `PreferenceToArgilla`
  src/distilabel/steps/argilla/preference.py
  src/distilabel/steps/argilla/text_generation.py
  tests/unit/steps/argilla/test_preference.py
Labels: fix, argilla
