Repository argilla-io/distilabel, pull requests merged in 2024-10, with the labels that each got.

#925 Add Tasks to replicate `APIGen`
  docs/assets/tutorials-assets/overview-apigen.jpg
  docs/sections/pipeline_samples/index.md
  docs/sections/pipeline_samples/papers/apigen.md
  examples/lib_apigen.py
  examples/pipeline_apigen.py
  mkdocs.yml
  src/distilabel/distiset.py
  src/distilabel/llms/_dummy.py
  src/distilabel/steps/__init__.py
  src/distilabel/steps/generators/data_sampler.py
  src/distilabel/steps/generators/huggingface.py
  src/distilabel/steps/tasks/__init__.py
  src/distilabel/steps/tasks/apigen/__init__.py
  src/distilabel/steps/tasks/apigen/execution_checker.py
  src/distilabel/steps/tasks/apigen/generator.py
  src/distilabel/steps/tasks/apigen/semantic_checker.py
  src/distilabel/steps/tasks/apigen/utils.py
  src/distilabel/steps/tasks/templates/apigen/generator.jinja2
  src/distilabel/steps/tasks/templates/apigen/semantic_checker.jinja2
  src/distilabel/utils/mkdocs/components_gallery.py
  tests/integration/test_generator_and_sampler.py
  tests/unit/steps/generators/test_data_sampler.py
  tests/unit/steps/tasks/apigen/__init__.py
  tests/unit/steps/tasks/apigen/_sample_lib/final_velocity.py
  tests/unit/steps/tasks/apigen/_sample_lib/get_value.py
  tests/unit/steps/tasks/apigen/_sample_module.py
  tests/unit/steps/tasks/apigen/test_execution_checker.py
  tests/unit/steps/tasks/apigen/test_generator.py
  tests/unit/steps/tasks/apigen/test_semantic_checker.py
  tests/unit/steps/tasks/apigen/test_utils.py
Labels: enhancement

#934 Pretty print
  docs/assets/images/sections/how_to_guides/tasks/task_print.png
  docs/sections/how_to_guides/basic/task/index.md
  src/distilabel/steps/tasks/base.py
  src/distilabel/steps/tasks/complexity_scorer.py
  src/distilabel/steps/tasks/evol_instruct/base.py
  src/distilabel/steps/tasks/evol_instruct/generator.py
  src/distilabel/steps/tasks/evol_quality/base.py
  src/distilabel/steps/tasks/improving_text_embeddings.py
  src/distilabel/steps/tasks/magpie/generator.py
  src/distilabel/steps/tasks/quality_scorer.py
  src/distilabel/steps/tasks/ultrafeedback.py
  tests/integration/test_prints.py
Labels: enhancement, question

#926 Add `CLAIR` task
  docs/assets/pipelines/clair.png
  docs/sections/pipeline_samples/index.md
  docs/sections/pipeline_samples/papers/clair.md
  mkdocs.yml
  src/distilabel/steps/tasks/__init__.py
  src/distilabel/steps/tasks/clair.py
  src/distilabel/steps/tasks/templates/clair.jinja2
  tests/unit/steps/tasks/test_clair.py
Labels: enhancement

#766 Add cache at `Step` level
  src/distilabel/mixins/signature.py
  src/distilabel/pipeline/_dag.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/batch.py
  src/distilabel/pipeline/batch_manager.py
  src/distilabel/pipeline/local.py
  src/distilabel/pipeline/ray.py
  src/distilabel/pipeline/step_wrapper.py
  src/distilabel/pipeline/write_buffer.py
  src/distilabel/steps/base.py
  tests/integration/test_caching_steps.py
  tests/integration/test_prints.py
  tests/unit/conftest.py
  tests/unit/pipeline/conftest.py
  tests/unit/pipeline/test_base.py
  tests/unit/pipeline/test_batch_manager.py
  tests/unit/pipeline/utils.py
  tests/unit/steps/argilla/test_base.py
  tests/unit/steps/argilla/test_preference.py
  tests/unit/steps/argilla/test_text_generation.py
  tests/unit/steps/tasks/evol_instruct/test_base.py
  tests/unit/steps/tasks/evol_instruct/test_generator.py
  tests/unit/steps/tasks/evol_quality/test_base.py
  tests/unit/steps/tasks/magpie/test_base.py
  tests/unit/steps/tasks/magpie/test_generator.py
  tests/unit/steps/tasks/test_base.py
  tests/unit/steps/tasks/test_pair_rm.py
  tests/unit/steps/test_base.py
Labels: improvement

#1022 Fix `IndexError` when overriding inputs and `group_generations=False`
  src/distilabel/steps/base.py
  tests/unit/steps/tasks/test_base.py
Labels: fix

#1029 Add common typing module
  src/distilabel/typing.py
Labels: improvement

#1037 Fix not handling list of all primitive types in `SignatureMixin`
  examples/arena_hard.py
  examples/deepseek_prover.py
  examples/structured_generation_with_instructor.py
  examples/structured_generation_with_outlines.py
  src/distilabel/__init__.py
  src/distilabel/mixins/signature.py
Labels: fix

#1039 Add `dataset_batch_size` argument
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/pipeline/ray.py
  tests/unit/pipeline/test_base.py
Labels: enhancement
