Repository argilla-io/distilabel, pull requests merged in 2024-09, with the labels that each got.

#937 Refactor of MinHash to work with a single class and fix the shelve backend
  src/distilabel/steps/__init__.py
  src/distilabel/steps/filtering/_datasketch.py
  src/distilabel/steps/filtering/minhash.py
  tests/integration/test_deduplication.py
  tests/unit/steps/test_filtering/test_minhash.py
Labels: enhancement, fix

#936 Update `make_generator_step` to set pipeline to step and add edge to steps in trophic level 1
  src/distilabel/pipeline/_dag.py
  src/distilabel/pipeline/base.py
  src/distilabel/steps/generators/utils.py
  tests/unit/steps/generators/test_utils.py
Labels: enhancement

#939 Add `CombineOutputs` step
  docs/api/pipeline/utils.md
  docs/api/step_gallery/columns.md
  mkdocs.yml
  src/distilabel/steps/__init__.py
  src/distilabel/steps/columns/combine.py
  src/distilabel/steps/columns/expand.py
  src/distilabel/steps/columns/group.py
  src/distilabel/steps/columns/keep.py
  src/distilabel/steps/columns/merge.py
  src/distilabel/steps/columns/utils.py
  src/distilabel/steps/embeddings/embedding_generation.py
  src/distilabel/utils/mkdocs/components_gallery.py
  tests/unit/steps/columns/__init__.py
  tests/unit/steps/columns/test_combine.py
  tests/unit/steps/columns/test_group.py
Labels: enhancement

#940 fix: regex expression in POSITIVE_NEGATIVE
  src/distilabel/steps/tasks/sentence_transformers.py
Labels: fix

#941 Fix all replicas had the same `_llm_identifier` for `CudaDevicePlacementMixin`
  src/distilabel/llms/mixins/cuda_device_placement.py
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/step_wrapper.py
Labels: fix

#945 Fix empty load stage when two `GlobalStep`s are chained
  src/distilabel/pipeline/_dag.py
  tests/unit/pipeline/test_dag.py
Labels: fix

#950 Add `system_prompt` attribute to `TextGeneration`
  src/distilabel/steps/tasks/text_generation.py
  tests/unit/steps/tasks/test_text_generation.py
Labels: enhancement, deprecation

#946 Add step to deduplicate records based on embeddings
  src/distilabel/steps/__init__.py
  src/distilabel/steps/embeddings/nearest_neighbour.py
  src/distilabel/steps/filtering/embedding.py
  src/distilabel/steps/generators/huggingface.py
  src/distilabel/steps/generators/utils.py
  tests/integration/test_embedding_dedup.py
  tests/unit/steps/filtering/test_embeddings.py
Labels: enhancement

#955 Add more generation parameters to `vLLM`
  src/distilabel/llms/vllm.py
Labels: enhancement

#965 Fix `Magpie` generating different columns names depending on `LLM` output
  src/distilabel/steps/tasks/magpie/base.py
  tests/unit/steps/tasks/magpie/test_base.py
Labels: fix

#969 Add `logging_handlers` argument
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/local.py
  src/distilabel/pipeline/ray.py
  src/distilabel/utils/logging.py
Labels: enhancement

#973 [DOCS] Add tips in the docs to avoid overloading Free Serverless Endpoints
  docs/sections/getting_started/faq.md
  scripts/install_cpu_vllm.sh
  src/distilabel/llms/huggingface/inference_endpoints.py
  src/distilabel/utils/docstring.py
Labels: documentation

#948 Add `TextClassification`, `UMAP`, `DBSCAN` and `TextClustering` tasks
  pyproject.toml
  scripts/install_dependencies.sh
  src/distilabel/steps/__init__.py
  src/distilabel/steps/clustering/__init__.py
  src/distilabel/steps/clustering/dbscan.py
  src/distilabel/steps/clustering/text_clustering.py
  src/distilabel/steps/clustering/umap.py
  src/distilabel/steps/generators/utils.py
  src/distilabel/steps/tasks/__init__.py
  src/distilabel/steps/tasks/base.py
  src/distilabel/steps/tasks/text_classification.py
  src/distilabel/utils/itertools.py
  src/distilabel/utils/mkdocs/components_gallery.py
  tests/unit/steps/clustering/__init__.py
  tests/unit/steps/clustering/test_dbscan.py
  tests/unit/steps/clustering/test_text_clustering.py
  tests/unit/steps/clustering/test_umap.py
  tests/unit/steps/tasks/test_text_classification.py
Labels: enhancement

#974 [FEATURE] Simplify customizing the `TextGeneration` task with custom prompts
  src/distilabel/steps/tasks/text_generation.py
  tests/integration/test_offline_batch_generation.py
  tests/unit/steps/tasks/test_text_generation.py
Labels: enhancement

#981 Update `system_prompt` attribute for adding probabilities in `MagpieBase`
  src/distilabel/steps/tasks/magpie/base.py
  src/distilabel/steps/tasks/magpie/generator.py
  tests/unit/steps/tasks/magpie/test_base.py
  tests/unit/steps/tasks/magpie/test_generator.py
Labels: improvement

#982 Fix unloading steps with more than 1 replica
  src/distilabel/pipeline/base.py
  src/distilabel/pipeline/step_wrapper.py
Labels: fix

#983 Fix missing `system_prompt_key` column in `Magpie` tasks
  src/distilabel/steps/tasks/magpie/base.py
  tests/unit/steps/tasks/magpie/test_base.py
Labels: fix

#992 Fine personas socialai tutorial
  docs/sections/pipeline_samples/examples/fine_personas_social_network.md
  examples/finepersonas_social_ai.py
  mkdocs.yml
  pdm.lock
  pyproject.toml
Labels: documentation

#966 feat: add basic draw implementation to pipline
  docs/assets/images/sections/how_to_guides/basic/pipeline.png
  docs/sections/how_to_guides/basic/pipeline/index.md
  src/distilabel/pipeline/_dag.py
  src/distilabel/pipeline/base.py
  src/distilabel/steps/generators/huggingface.py
  tests/unit/pipeline/test_dag.py
Labels: enhancement

#999 [DOCS] Add developer documentation section in the docs
  docs/sections/community/contributor.md
  docs/sections/community/developer_documentation.md
  mkdocs.yml
Labels: documentation

#1009 Fix `vllm` installation in CI
  scripts/install_cpu_vllm.sh
Labels: fix, ci

#984 Add example of custom text generation step in quickstart
  docs/sections/getting_started/quickstart.md
Labels: documentation
