Repository argilla-io/distilabel, pull requests merged in 2024-01, with the labels that each got.

#204 Add `VertexAILLM` & `VertexAIEndpointLLM` classes
  .github/workflows/test.yml
  pyproject.toml
  src/distilabel/llm/__init__.py
  src/distilabel/llm/base.py
  src/distilabel/llm/google/__init__.py
  src/distilabel/llm/google/vertexai.py
  src/distilabel/llm/huggingface/inference_endpoints.py
  src/distilabel/llm/huggingface/transformers.py
  src/distilabel/llm/llama_cpp.py
  src/distilabel/llm/openai.py
  src/distilabel/llm/vllm.py
  src/distilabel/utils/imports.py
  tests/llm/google/__init__.py
  tests/llm/google/test_vertexai.py
  tests/llm/test_base.py
Labels: enhancement

#210 Relax `LLMPool` check to match parent `Task` instead
  src/distilabel/llm/base.py
  tests/llm/test_base.py
Labels: improvement

#214 Align `README.md` with `docs/` and minor fixes / improvements
  .cache/plugin/social/0996050c15d38684e49df59e0a486d5a.png
  .cache/plugin/social/0c444ce31177c04da404ef4007686864.png
  .cache/plugin/social/0f8298b45055d1e7e6d9024fc6eb8f41.png
  .cache/plugin/social/0fd21192a2bf8f4699a3e81b794b49df.png
  .cache/plugin/social/190bb622d06dfcb4edbad730e175b75b.png
  .cache/plugin/social/1b86809fd6477ffd4fa4c2de8a44f737.png
  .cache/plugin/social/25c216e55c7579c65fc5160aece49b7f.png
  .cache/plugin/social/2f0d20c696c00a973de2e19085cdcd22.png
  .cache/plugin/social/347988768de9ccf31fe986247021dc11.png
  .cache/plugin/social/39088edb59ad4bb87e288a9c90bdf63a.png
  .cache/plugin/social/5470f3754486a9c84ad9951105cadf01.png
  .cache/plugin/social/56ee2920338f407aabbde0f70353c86d.png
  .cache/plugin/social/60cd35f4b6c9eac8a258a1eb2dc189b0.png
  .cache/plugin/social/624f403776bfaef5cbfb1fa7cb8fc7c5.png
  .cache/plugin/social/6c070f1fe38d98fb31b937389328edc4.png
  .cache/plugin/social/70527f357a5fda0c8fd50b62a2bc10df.png
  .cache/plugin/social/73072d4d982e6125b065108aa4596311.png
  .cache/plugin/social/790235402351a03da7370dc64c692b8b.png
  .cache/plugin/social/7904977e796fecbb4f1e3f2d9593c212.png
  .cache/plugin/social/7939f5a6a902226ee28f0c720180e0b3.png
  .cache/plugin/social/7f6cda5067d4a056913ef35fa2c2bc2f.png
  .cache/plugin/social/80fae5521d7afd57a08bc56b611f6a00.png
  .cache/plugin/social/88281aae3b3fbe796ad78ca3e81290a4.png
  .cache/plugin/social/8e2cbfbd4ac745a8e931065f467386cc.png
  .cache/plugin/social/9186c7732b2c035cf64d16425e7ef6a8.png
  .cache/plugin/social/983cc182dee00ddcdd201690d853dd4b.png
  .cache/plugin/social/Roboto-Black.ttf
  .cache/plugin/social/Roboto-BlackItalic.ttf
  .cache/plugin/social/Roboto-Bold.ttf
  .cache/plugin/social/Roboto-BoldItalic.ttf
  .cache/plugin/social/Roboto-Italic.ttf
  .cache/plugin/social/Roboto-Light.ttf
  .cache/plugin/social/Roboto-LightItalic.ttf
  .cache/plugin/social/Roboto-Medium.ttf
  .cache/plugin/social/Roboto-MediumItalic.ttf
  .cache/plugin/social/Roboto-Regular.ttf
  .cache/plugin/social/Roboto-Thin.ttf
  .cache/plugin/social/Roboto-ThinItalic.ttf
  .cache/plugin/social/abe7fe958897ac2f79775b4bd6a2378a.png
  .cache/plugin/social/ad99588f3e598c48ea76ca1fabe8060a.png
  .cache/plugin/social/b33b84d5e78c9bcf70b8253892a2c354.png
  .cache/plugin/social/b47e610316d75b0e21a017adbba9b817.png
  .cache/plugin/social/bf90aba6d296f4f9fa4ff1741cf295c1.png
  .cache/plugin/social/d3c80c661fe824d6f00f2733e96d04cc.png
  .cache/plugin/social/d61181e428c686f8c62d7814e4fd2947.png
  .cache/plugin/social/d9afa3607cba0851e593b377dbf41f56.png
  .cache/plugin/social/ddc294cba74f433e4c7f89529327a5bd.png
  .cache/plugin/social/e0a7d7eabd32925a2570663747ae9984.png
  .cache/plugin/social/ea1614f4e981e056e3139a51469180d2.png
  .cache/plugin/social/ec10edb2769f30ccd2de90da91682169.png
  .cache/plugin/social/f95d7edaa460c11de9ec67313b0ee243.png
  .gitignore
  .pre-commit-config.yaml
  README.md
  docs/index.md
  license_header.txt
Labels: documentation, fix

#215 Add `TogetherInferenceLLM`
  README.md
  docs/index.md
  docs/snippets/technical-reference/llm/together_inference_generate.py
  docs/technical-reference/llms.md
  examples/pipeline-together-inference.py
  src/distilabel/llm/__init__.py
  src/distilabel/llm/together.py
  src/distilabel/tasks/base.py
  src/distilabel/utils/imports.py
Labels: fix, integrations

#216 Add checking valid `inputs` before calling `_generate`
  src/distilabel/llm/base.py
  src/distilabel/pipeline.py
  src/distilabel/utils/futures.py
  tests/llm/test_base.py
Labels: fix

#217 Add `TogetherInferenceLLM` tests
  .github/workflows/test.yml
  pyproject.toml
  src/distilabel/llm/together.py
  tests/llm/test_together.py
Labels: fix, test

#222 Add Vertex AI `LLM`s documentation
  docs/snippets/technical-reference/llm/llmpool.py
  docs/snippets/technical-reference/llm/processllm.py
  docs/snippets/technical-reference/llm/together_inference_generate.py
  docs/snippets/technical-reference/llm/vertexaiendpointllm_generate.py
  docs/snippets/technical-reference/llm/vertexaillm_generate.py
  docs/snippets/technical-reference/llm/vllm_generate.py
  docs/snippets/technical-reference/pipeline/pipeline_llmpool_processllm_1.py
  docs/snippets/technical-reference/pipeline/pipeline_llmpool_processllm_2.py
  docs/snippets/technical-reference/pipeline/pipeline_llmpool_processllm_4.py
  docs/technical-reference/llms.md
Labels: documentation

#223 Documentation review
  docs/index.md
  docs/scripts/gen_ref_pages.py
  docs/technical-reference/pipeline.md
  src/distilabel/pipeline.py
  src/distilabel/tasks/critique/prometheus.py
  src/distilabel/tasks/critique/ultracm.py
  src/distilabel/tasks/preference/judgelm.py
  src/distilabel/tasks/preference/ultrafeedback.py
  src/distilabel/tasks/preference/ultrajudge.py
  src/distilabel/tasks/prompt.py
  src/distilabel/tasks/text_generation/principles.py
  src/distilabel/tasks/text_generation/self_instruct.py
Labels: documentation

#224 Rename `for_text_quality` to `for_overall_quality` method in `UltraFeedbackTask`
  docs/snippets/technical-reference/tasks/openai_for_overall_quality.py
  docs/technical-reference/tasks.md
  examples/pipeline-llamacpp-and-openai-process.py
  examples/pipeline-llamacpp-and-openai.py
  examples/pipeline-vllm-and-openai.py
  src/distilabel/pipeline.py
  src/distilabel/tasks/preference/ultrafeedback.py
Labels: fix, improvement

#227 Fix `rating` parsing in `RatingToArgillaMixin.to_argilla_record`
  src/distilabel/tasks/critique/base.py
  src/distilabel/tasks/mixins.py
  src/distilabel/tasks/preference/ultrafeedback.py
Labels: fix

#226 Add badges to readme
  README.md
  docs/assets/distilabel-badge-dark.png
  docs/assets/distilabel-badge-light.png
Labels: documentation

#264 Add new functionality to binarize preference datasets directly from distilabel
  docs/snippets/technical-reference/pipeline/prepare_dataset_binarize_random.py
  docs/snippets/technical-reference/pipeline/prepare_dataset_binarize_worst.py
  docs/technical-reference/pipeline.md
  src/distilabel/utils/__init__.py
  src/distilabel/utils/dataset.py
  tests/test_dataset.py
Labels: enhancement, team: ml

#288 Add new serialization strategy
  pyproject.toml
  src/distilabel/dataset.py
  src/distilabel/tasks/base.py
  src/distilabel/utils/dataset.py
  src/distilabel/utils/serialization.py
  tests/tasks/test_serialization.py
  tests/test_dataset.py
Labels: team: ml

#305 Review `OllamaLLM` and `TogetherInferenceLLM`
  src/distilabel/llm/ollama.py
  src/distilabel/llm/together.py
  tests/llm/test_together.py
Labels: fix

#308 Add missing VertexAI information within `README.md` and `docs/index.md`
  README.md
  docs/index.md
  src/distilabel/llm/google/vertexai.py
Labels: documentation

#313 Add `Improving Text Embeddings with LLMs` tutorial
  docs/index.md
  docs/technical-reference/tasks.md
  docs/tutorials/improving-text-embeddings-with-llms.ipynb
  examples/pipeline-openai-wizardlm-equal-prompts.py
Labels: documentation

#314 Add `validate_prompts` method to LLMs to help validating the prompts
  docs/snippets/technical-reference/llm/validate_prompts_1.py
  docs/snippets/technical-reference/llm/validate_prompts_2.py
  docs/technical-reference/llms.md
  src/distilabel/llm/base.py
  tests/llm/test_base.py
Labels: enhancement

#275 Custom Task Documentation
  docs/snippets/technical-reference/tasks/custom_task_selfinstruct_haikus.py
  docs/snippets/technical-reference/tasks/custom_task_selfinstruct_haikus_docs.py
  docs/snippets/technical-reference/tasks/custom_task_text_generation_oss.py
  docs/snippets/technical-reference/tasks/custom_task_text_generation_wizardlm.py
  docs/technical-reference/tasks.md
Labels: documentation

#317 Include rationale of the model responses on `prepare_dataset` if available
  docs/technical-reference/pipeline.md
  pyproject.toml
  src/distilabel/utils/dataset.py
  tests/test_dataset.py
Labels: enhancement
